* 800 Years Predictions – Hazrat Naimat Ullah Shah Wali.
https://laxmimadhav.wordpress.com/2016/09/30/800-years-predictions-hazrat-naimat-ullah-shah-wali/

September 30, 2016 LAXMIMADHAV	
Page-1: Title Page
 
Page-2 to Page-8 (of original urdu book)

PREFACE
Hafiz Muhammad Sarwar Nizami’s
(Edited with best of Intentions)

My friends,
The above-mentioned words of God means that Indeed the friends of Allah are neither in fear nor in grief.
Fear results from not knowing the future and grief results from what happened in one’s past… The glory of the friends of Allah is that neither they feel grief on past events nor are they afraid of the future because when they become friends of Allah, Allah becomes a friend of them.

… Difference between Wali and Walayat should be kept in mind. Walayat (Sainthood) is a position, a station that is assigned to a Wali (Saint). i.e. Wali has his own existence and Walayat has its own existence. Take an example of Ilm (knowledge) and A’alim (Scholar). A’alim is the one who has been given the knowledge. Similar is the relation in Nabuvat (Prophet hood) and Nabi (Prophet). Prophet is the one who has been assigned the station of Prophet hood.

Now please note the difference in the status / knowledge of Prophet hood and Sainthood.

Prophet (PBUM) said:
I’ve come to known whatever is in the skies and whatever is in the earths (worlds). I.e. I see the universe as I see my palm.
Whereas, Walayat said: Syedna Abdul-Qadir Jillani R.A said: I see the universe as I see a grain of rice on my palm.

Difference in both statements should be noted. The sayings of Prophet hood are like a plain palm whereas the sayings of Sainthood are like a grain on palm. When a grain of rice is placed on a palm, one dimension (down) out of six dimensions (left, right, front, back, up and down) is invisible to the eyes. Whereas, there is no dimension hidden on plain palm. Thus, where Sainthood reaches its top point (means where Sainthood reaches to top limit), there begins the Prophet hood. Similarly, where materialism reaches its top point (means where materialism reaches to top limit), there starts the Roohaniat (Spiritualism)
Let’s ponder over the knowledge of Allah who is infinite and whose attributes are infinite. It is not possible that God who is infinite has limited attributes or God who is limited has infinite attributes.

God knows everything from the beginning. For Him everything is already known (Ma’loom – in information). Ilm (Knowledge) comes later. That is why friends of Allah say that Ma’loom is superior to Ilm. For a man, Ilm comes first and Ma’loom is secondary. For Allah, Ma’loom comes first and Ilm comes later.

Sheikh Akbar Muhayudin Al-Arabi states that information of Allah that were originated from the Nafs (soul?) of Allah granted knowledge to Allah. Because Allah is infinite, unique, One, unlimited and is not dependent on anyone, therefore He himself is A’alim. All Knowledge, All Information (whatever is there to know) and the Knower, all that 3 levels, belong to Allah who is infinite.

Holy Hadeeth is:

(In the beginning) There was nothing besides Allah. So when there was nothing with him (in the beginning), therefore there is nothing with him (now)… that is when there was nothing and only Allah existed, he knew everything. To him, there was nothing that was hidden (or unknown). He was Aleem (an attribute, meaning knower); he is Aleem and will remain Aleem. There is no restriction of past, present and future… neither he is bound by Time nor by space. (Similarly) his attributes are neither bound by time nor by space.

Allah says in Al-Quran:
Indeed Allah encompasses everything with Ilm.

His knowledge is pure and without any medium or source. Man through medium knows the knowledge of Smoke and Fire. By seeing the smoke, knowledge of man informs the man that there is a fire there. The existence of smoke denotes the existence of fire i.e. the knowledge of Fire is gained through the medium of smoke. Knowledge of Allah is pure and without a medium.
My friends,

Allah says in Quran:
We have stated everything openly. In Lohe-Mahfooz (The Tablet. The Akashic Records)

And Prophet Muhammad S.A.W (PBUH) said that Allah Ordered the Pen:
O Pen! Write down everything that is known to me and whatever is going to happen till the Day of Judgment. Allah ordered and the Pen obeyed.

Imam Hussain R.A. Said in “Meerat-ul-Aa’rifeen”:
All praise to Allah who extracted (Ilm) from “Noon” (an alphabet) and wrote it in (through) the mouth of Pen.

Allah says in Al-Quran:
Let’s understand it. Ink is the status of knowledge where all the information is hidden or a status where all alphabets, words, sayings and whatever is said is hidden but cannot be separated and everything is already known to the Self of God (or the soul of God) even the level of ink itself. Then all those information was described through the mouth of the pen and all those information were saved and separated in sentences.

That is why we see in Hadeeth:
The first ever creation was my Noor (light). First ever creation was the Pen. First ever creation was the intellect (wisdom or intelligence).

All three levels, stations and attributes belong to one personality. i.e. Hazrat Muhammad S.A.W.
Allah took all three levels and swore that O Muhammad S.A.W., I sware of the station when you were at level of Ink, and I sware of the station when you were at the level of the Pen and I sware of the station when you were at the level of Sentence.

Note: Alphabets, Words, and what was said all three are located in a sentence.

Allama Iqbal said (Bal-e-Jibreel Poem: Read complete Poem Zauq-o-Shauq ):

Allah said:
We have openly described everything in Lohe-Mahfooz (Tablet, Akashic Record)

Jalaludin Rumi R.A. Said:
Lohe-Mahfooz is in front of friends of Allah (Walis). Whatever is written there is pure and without error.
Naimutullah Shah Wali r.a. was a great Wali of Allah. Knowledge of Jaffar (Alphabets, words, numerology) was his slave. It is a small miracle that 800-year-old predicted events are happening to the letter. Some sources suggest that he wrote more than 2000 poetic stanzas out of which the translator/author has 248 stanzas. Some stanzas are incomplete and singular.

He traveled through many cities to reach Kashmir. There, he passed away.

He said:
Lord Curzon (Viceroy) banned this prediction stating: how it is possible that we only rule India for 100 years?
The stanzas of qaseeda are very rare now. The lovers of Awliya protected the stanzas. It is saved in manuscripts, and in memory.

Author thought about publishing the qaseeda for a long time. Now with the help of Man Ali Hassan, it will be published and the reader will enjoy it.

Please remember me in your prayers,
Hafiz Muhammad Sarwar Nizami, Layalpur (Now Faisalabad, Pakistan) – 1972
(Now The Predictions Part)
Page-9 – Family Tree of Mogal Empire (Mughal Dynasty)
 
Page-10

1. I am telling the truth, there will be a King in this world. Taimur his name and he will be the Conqueror.(l)
2. After Him, Meeran Shah appear in this world who will be the friend of the conqueror Taimur Shah.(2)
3. When he passes away from this world, and then will appear the King of Humans and Jinns (Ginns).(3)
4. After Him, Umer Sheikh will be the King and he’ll be a claimer and a very Kind person.
5. After that, Umer Bin Sheikh will be the owner of this land and he’ll indulge into a lot of riches and luxuries.
Page-11

6. After him shall come The King Babar who will be the king of Kabul, later he will appear in Delhi as a ruler of India.
7. After Sikandar [Lodhi], till the time of Ibrahim Shah (King), Behold there will be unrest and discord in his Kingdom.(4)
8. Then the God will appoint Humayun as the King of India but meanwhile an Afghan will appear.(5)
Page-12

9. Then God will grant kingdom to Humayun. Then will happen an incident in Humayun’s life. Meanwhile an Afghan will appear. Afghan’s name shall be Sher Shah. Humayun will run to the land of Iran, to the bloodline of the prophet so that they can honor humayun. The Iranian King will help Humayun so that Humayun can be honored as a King. By the time Humayun will attack India again, SherShah will be dead and his son will be ruling the land.(6)
10. So Humayun will conquer India. Then will come Akbar as the King of the land.(7)
Page-13
Explanation (In blue color numbering by H.M Sarwar Nizami himself as in urdu book) 

(1) History: Taimur Shah attacked India in 1398. Muhammad Tughlaq was the King of India at that time. After his defeat he fled and Taimur Shah got hold of India. He returned to Samarkand later. Died in 1412
(2) History: Meeran Shah = Sultan Muhammad Mirza
(3) History: That is Sultan Abu Saeed Mirza who was brave and Powerful.
(4) History: Ameer Taimur left his second-in-command Syed Khyzr Shah. He and 3 successors till Ala-ud-din were governors. From 1414 to 1451, this family of Syeds governed. Lodhi Family ruled from 1414-1451.
(5) History: Zaheer-uddin-Babar was from the fifth Generation of Taimur… Because of a dispute with Ibrahim Lodhi, Dolat Khan (the ruler of Punjab) and Rana Sanga (the ruler of Mewar) invited Babar to attack India. Babar saw it as an opportunity and he attacked India in 1526. After four unsuccessful attempts, he succeeded in the fifth. His Govt. was from 1526-1530
(6) History: Sher Shah was the son of a landlord called Hassan Khan. He was in service of the ruler of Bihar Province. Later he became ruler by force. Because of this act, Humayun attacked Sher Shah in 1540 but got defeated. Humayun fled to Iran. In 1545, with the aid of Iran, humayun conquered Kabul and Qandhar. Humayun conquered India by the year 1555.
(7) History: Jalal-ud-Din Muhammad Akbar Ruled India from 1556-1605
——————————————————————————————-

11. Then Jahangeer shall be the King. He will sit on the Throne like the bright sun.(8)
12. When He will leave the world, Shah japan, The second Conqueror will appear.
13. Will rule for less than 40 years and his son will sit on the throne in front of his eyes.
14. There will be unrest and discord in his time and the country will be in bad conditions. Availability of Food will be surprising.
15. When the world will be like this, the people will be extremely worried. The Jupiter will be like a flame thrower
16. He will rule for 20 years till the youngest of his sons will appear.
17. His powerful voice will fill the world. He will take care of the people.(9)
Page-14

18. Then the God will show his decision. Know that his name will be Muazam. He will appear on the scene.(10)
19. During his time, the people will be united, peace shall be everywhere. He will be like an ointment to the wounds of the land.
20. He will rule for few years then pass away. His son will become King.(11)
Page-15

21. With his arrival, there will come balance. Unhappiness and jealousy will fade away. There will be happiness everywhere.
22. Then will come an extremely powerful king called Muhammad. will come to India and become ruler.(12)
23. The time of Muhammad’s Kingship is 21 years. Then will come a ruler of the rulers.(13)
24. Nadir Shah will come from km. He will occupy the Throne of India by force. Mass killings of Delhi’s population will occur.(14)
—————————————————————————-
(8) History: Jahangeer Noor-ud-din Muhammad ruled from 1605-1627

(9) History: Shah-Japan Shahab-ud-din Muhammad ruled from 1627-1658. He had 2 sons. Dara-Shikoh and AurangZeb. There was discord and fighting in between them. The people were also divided in two camps. In 1650, there was a fearsome war in between AurangZeb and Dara. Dara fled and got defeated. AurangZeb continued the manhunt. Malik jeevan an (the ruler of Sindh) handed Dara over to AurangZeb. Dara was executed. AurangZeb Alamgeer Mohay-ud-din ruled from 1658-1707.
(10) History: Bahadur Shah Muazam ruled from 1707-1712.
(11) History: The son of Bahadur Shah Muazam was Farrukh Seer. Who ruled from 1712-1719
(12) History: Muhammad Shah ruled India from 1719-1740.
(13) History: Muhammad Shah ruled for exactly 21 years
(14) History: Nadir Shah attacked India in 1739. Nadir Shah used to be a herd-keeper by profession. He progressed and became the king of Iran. Later he conquered Kabul and Qandhar. Seeing a weak kingdomship of India, he attacked in 1739. Muhammad Shah was defeated and he asked for truce. Nadir Shah entered Delhi as a guest of Muhammad Shah. After few days, a rumor spread that Nadir Shah is murdered. So the soldiers of Delhi started killing the army of Nadir Shah. Nadir Shah got extremely angry and he ordered the Mass murder in Delhi. In 12 hours, approx. 150,000 people were murdered. At the request of Muhammad Shah, this mass murder was stopped. Looting and destruction continued for 2 months. Nadir Shah returned to Iran after getting Taoos (The Throne), Kohinoor Diamond and lot of treasure.
————————————————————————————–

Page-16
25. When the ruler of India will about to leave this world to continue his journey forward, his family will be in problems.
26. Then will come mighty Ahmad the King. He will rule India and people will obey his orders.(15)
Page-17

27. When Akbar will be the King, there will appear a Saint.
28. His name would be NANAK. Populace will give attention to him. This powerful Fakeer [seer] will become famous.
29. He will be famous in Punjab and Sikh nation will be among his followers. He will be the spiritual leader of this nation.(16)
30. The Sikh Nation will be cruel towards Muslims and this cruelty and innovation will appear in 40 years.(17)
Page-18

31. Then The Christians [English] will occupy India. Their order will be obeyed there for about 100 years.(l8)
32. When the cruelty and one-sidedness will reach its highest point, the Christians will harm the religion.(l9)
33. The Christians [English] will be involved in a war with Germany. The sign of destruction and chaos will appear. (20)
34. The Christians (England) will win the war against Germany but the war will weaken their system of rule.
Page-19

35. The Christians will leave the India but before doing so, they will sow the life-taking discord among the populace.
36. India will be divided into two countries and for this reason the blood of humans will run. Destruction and anarchy will rule beyond imagination.

———————————————————————————————
(15) History: After the death of Muhammad Shah (Rangeela), his son Ahmad Shah was the ruler for few years. All the ministers were parties in chaos and wars. Rohails revolted. To curb them, Ahmad Shah had to seek assistance of Marhatas. In 1752, Ahmad Shah Durram attacked Punjab. He was the victor. Punjab became a part of Durrani Empire. In 1758, one of the his ministers Ghazi-ud-din son of Asif jah (Nizam-ul-Mull, Ruler of Haiderabad Dakar) conspired against him, blinded him, and then Alm Shah aka Alamgeer the Second became the king. He ruled from 1759-1806. Akbar the Second ruled from 1806-1837 and Bahadur Shah Zafar the Second was the ruler from 1837-1857. There is no Stanza was found about them.

(16) History: Baba Guru Nanak was born in 1441 and died in 1528.
(17) Maybe 40 years period is after the death of Guru Nanak – Editor
(18) History: England ruled India for about 100 years. Lord Curzon (Viceroy of India) declared a ban (by law) on these predictions.
(19) History: During the reign of English a scholar called Mirza Ghulam Ahmad sowed the seeds of discord in the religion of Islam.
(20) History: WWI was from 1914-1918. After 21 years, WWII was fought from 1939-1945. Germany was involved in both the fights.
————————————————————————–
37. A lot of Muslims will leave their homes due to the wrath of the Hindus. They will migrate. The dignity and honor of Muslims will be in ruins. Their women and girls will be kidnapped.
38. Muslims will be in peace in the area of their forefathers. After Punishment and problems, their destiny will appear.(21)
Page-20

39. The banner of Islam will be the prominent for 23 years. Then divine punishment will come upon them.
40. Their own land will become narrow for them. Destruction and anarchy will become their destiny.(22)
41. After their destruction. Allah will send blessings, victory and help from neighbors.(23)
42. An army of Mongols (24) will come from North to help. Iran and Turkey will help too.(25)
Page-21

43. This help will appear after the Pilgrimage.(26) When Allah will send the divine help from unknown.(27)
44. Divine help will turn the defeat into a victory. I am seeing all this with deep understanding. That Muslims will be the victor and successful.
45. When these predictions were made, it was the year 570 Hijra. So the God wills and will appear in the same manner. (28)
Page-22

46. When the cruelty and crime will be spread in his era, there will come a King of the west. He will be the real good administrator.(29)
———————————————————————————————-
(21) History: Pakistan got independence on August 14, 1947. The genocide, rape and kidnapping of girls and women is not a secret. The migrants sacrificed their lives and their wealth in order to get independence.

(22) History: Yahya an Ruled from March 1969-December 1971. East Pakistan was lost due to a war in between India and Pakistan on November 22, 1971. The war with West Pakistan started on December 3, 1971, resulted into destruction and chaos in Pakistan. Yahya Khan’s incompetence and careless resulted into the loss of The Eastern Province and about 100,000 soldiers became POWs. About 1.5Million Bengali and non-Bengali were killed. Before that time, for 23 years, Islam and Muslims were safe and sound in this part of the world.
(23) Stanzas 41-42-43 describe the events of upcoming future war.– MC
(24) Maybe a reference to China — MC
(25) Possibly, Muslim warriors will join hands to repel the aggression and occupation of their lands. — MC
(26) 2008 pilgrimage was on December 9’s. 2009-2012 will be in the months of October-November -MC
(27) Probably, help will come from neighboring countries like Afghanistan, Iran, China and turkey. Saudi Arab, Libya, Egypt, Syria, Iraq, Jordan, and all other Middle Eastern Muslims will help Pakistan. People of knowledge categorize mankind into four classes. Aryans, Mongols, Ethiopians and Europeans. European people are white in complexion. Ethiopians are black. Aryans are people of Indo-pak and Middle East. Mongols are people from Indonesia and China. China is located in the north of Pakistan. China and Pakistan are considered friendly nations. For this reason, maybe Shah Naimatullah Wali is indicating Chinese nation as Mongols. Such help is to come after the 10 Zil-Hujj. We can assume that the equipment of war will arrive during Muharram. – Hafiz Nizami
(28) Based on this copy of qaseeda and on another different copy that I have, I assume that Naimat-ullah Shah wali always concluded a set of predictions by stating the date in the last stanza. -And Allah knows best- — MC
(29) Hafiz Nizami, The original compiler/translator commented that Since East Part of Pakistan got separated and became an independent country (Bangladesh), Naimat-ullah Shah continued with the future of the Western part of Pakistan. – MC
—————————————————————————————–

47. This Sword of the Lion of Ali (Sher-e-Ali or Sher-Ali) will wipe off the deniers. He will be the supporter of the religion of Muhammad S.A.W. He will be the protector of the country.(30)
48. There will be a great war in between him and the other. No doubt a large population will be killed.
49. The King of the western Part will be the victor on the basis of his weaponry. The defeat of the denier nation will be beyond anyone’s imagination.(31)
50. Islam will rule in India for 40 Years, then will come the anti-Christ [Dajjal] from the city of Asfahan.(32)
51. Listen Carefully, I explain to you that to destroy this anti-Christ [Dajjal] Isa (Yesu / Yeshua/ Jesus) will come and Imam [leader] of Last Era, Mahdi, will appear.
Page-23

52. Naimat-ullah Shah is aware of the secrets of the unseen therefore Indeed what he’s saying will appear in this world, universe and in that era.(33)

————————————————————————————————
(30) Commentary of Hafiz Nizami is quite long and a repetition of what was stated earlier. 

(31) Because some stanzas are missing here, so It is not clear if the seer was predicting the Afghan-Russia was or some future war yet to happen If No. 50 is the continuation of the 46-49, then this King has not yet arrived and the events are yet to occur. – MC
(32) A province of Iran. There’s a large population of Jews living in Iran. Some prophecies of the Prophet Muhammad S.A.W. clearly mention that the Anti-Christ will come out of Isphahan and will have 70,000 Jewish followers. – MC
(33) Unseen is a controversial issue among Muslims. Some say that no one can know the unseen. They forget that everything in this universe is running under a system. Allah has a system for ‘unseen’ as well. ‘Unseen’ is unseen and in the knowledge of Allah alone until Allah let it to be seen and known. Whatever Allah commands, it appears on the Lohe-Mahfooz (The Preserved tablet or Akashic records). Those who have the ability and permission can view it. Some can see the commands for one day, some for a week, some for a month, some for a year and some can view, as much as Allah wants them to. Predictions were made by the prophets, by the mystics and seers through out the history. Unknown is unknown until Allah let it to be known. -And Allah knows best- – MC
——————————————————————————————–
Page-24

53. I am looking at the power of the God (or ‘destiny’); I am looking at the condition of the world.
54. I am not saying this out of the knowledge of Astrology, but looking at it with the grace of Allah.
55. In Khurasan [Iran], Egypt, and Syria And in Iraq, seeing the evil of war.
56. All of them will be in poor condition. Although one in the Thousand, I am looking at.
57. Listening to a strange story, watching a city in great chaos.
58. Murder, destruction and countless army, left & right, I am looking at.
59. Lowest [mean] of the people in knowledgeable and expert works, I See
60. Religion is very week, bad habit of pride, I See
Page-25

61. Friends from every nation, in bad situation and are mourning
62. Rise and fall, appointment of Governors, two times, I see
63. Turks and Tajiks are the enemies of each other, I see
64. Lies, fraud and deceit everywhere, in elders and in young generation, I see
65. The value of good deeds is very very low. Flames at one place, I see
66. If today there is any peace, only in the mountains, I see
67. Although I am watching all this but am not worried. The joys ahead, I see
68. After this year, and some other years, I look at the world as in a movie theater.
69. A wise King as an honorable leader, I see.
Page-26

70. This year is not like the others. I am not seeing like someone see in aware state.
71. When the year “GHA” [Alphabet] and the ”RA” [Alphabet] will pass in years, I see a strange business (event).(34)
72. Dust & Rust on the mirror of self (hearts) of the people of this world, I see
73. Darkness of unbound and unlimited cruelty spreading through the Cruel of the cities, I see.
74. Sorrowful war and living Evil, in the middle and at the sides, I see.
75. Slave will be the Master and the Masters will become slaves, I see.
——————————————————————————–
(34) Referring to a system in ‘Jar’ (a knowledge of Alphabets and Numerology) in which Alphabets are assigned to years or the attributes of a certain alphabet commands a certain year. – And Allah Knows Best – MC

——————————————————————————–
76. This year the friend will be in trouble, his heart filled with sorrows, I see
77. At the face of Gold, there will be a new stamp. His “dirham” [currency] will be pure, I see.
78. All the rulers of the world are fighting with each other, I see.
79. The face of moon is dark, the heart of the Sun bleeding, I see.
80. Merchants in far off jungles, without companions and tired, I see.
Page-27

81. Hindu nation in poor conditions, I see. The cruelty of Turks and Tatars, I see.
82. Some trees of the garden of the world, without spring, without fruit, I see.
83. Then helping others and contentment, staying in seclusion is the best, I see
84. 0 the one who is addressed, don’t worry because in this trouble, the joy of meeting the FRIEND, I See.
85. When winter without fruits will pass, then shiny spring will come, I see.
86. When his [Friend’s] era will pass, his son as his souvenir, I see.(35)
87. The companions of this highly honored one shall be owners of crown [or living like Kings], I See.
88. The kings of all? realms will reach the heights of their rise, I see.
Page-28

89. His Works, his features, his knowledge and kindness, his wisdom and understanding will be same as the Prophet, I see.(36)
90. His White hand with Brightness and in it a Sword, I See.
91. Fragrance coming out of the gardens of Prophet’s way, I smell, the flower of the religion in bloom, I See.
92. 0 my Brother, this Rider’s rule for 40 years, I see.
93. Disobedient people embarrassed and ashamed, in front of this pious Imam [leader], I see
94. He will be the “Ghazi”(37), keeper of friendships, and destroyer of the enemies. The kind, friendly and humane, I see.
95. Beauty of the Way of the prophet and spread of Islam, strong and stable, I See.
96. The treasures of the Persian Kings and the Wealth of Alexander, being consumed in good works, I see.
Page-29
—————————————————————————–

(35) The ‘friend’ referred here can be Prophet Isa (A.S.) or Muhammad Mehdi R.A. -And Allah Knows Best — MC

(36) Definitely a reference to Muhammad Mehdi R.A. (The guided one) or his predecessor And Allah Knows Best  — MC
(37) The One who fought the wars and lives — MC
—————————————————————————-

97. He himself will be the Imam (Leader) and World will be on one axis (center).
98. Meem, Ha, Meem, Dal (Muhammad), his name shall be, this I see and read.
99. Because of him, the religion and the world will be filled and joyful, Lucky are the people, I see.
100. Mehdi of the time and Isa [Yesu/Yeshua/Jesus] of era, both are royal riders, I see.
101. World as a city, I see, personality as strong as Castle, I see.
102. My Sultan will have 7 Ministers, all of them will be successful, I see.
103. Refreshing drinks in the hands of the serving ones, I see.
104. The Steel swords of Rusty hearts, useless and scrap, I see
Page-30

105. Sheep with the Wolf and Deer with the Lion, staying in the same place,(38) I see.
106. The clever Turk in ecstasy, I see. His enemy is drunk, I see
107. Naimat Shah, Sitting alone, is seeing all this.

——————————————————-
(38) And not harming each. A golden Age — MC
——————————————————- 

NOTES
                           By Hafiz Muhammad Sarwar Nizami’s
Respected Elders,
In the above-mentioned Qaseeda (poetic story), Naimat-ullah Shah Wali R.A. used “May Beenam” as radeef. It means, “I am Looking at”. According to the knowledge of Sarf, its masdar is “Deedan”. “Deed” is its past tense and “baind” is its mazar’a. Because “May Beend” shows the present tense so when used as singular Mutakalam, it will become “May Beenam”. He’s a friend of Allah and is stating that “I am, looking at”.
‘To see’ is of two types. One is to see through physical eyes, the other is through inner spiritual eyes.

Maulana Ghulam Rasool Alampur Kotly r.a. Said:
Close these physical eyes that cannot do justice Open your inner eyes for salvation.
Page-31

‘To see’ from the physical eyes is to look through physical senses. ‘To see’ through spiritual eyes is to look through power of vision. The name of this power is ‘thought’. Thought process is of two types. One is a limited and the other is absolute. Limited thought is associated with physical me whereas absolute thought is beyond me. Everything that we see in our world is of high density. Sufi termed it as ‘the realm of bodies’. Whatever is present in the realms of bodies, all of it is present in the ‘realm of shapes’. However, all of the ‘realm of shapes’ cannot be present in the ‘realm of bodies’. Because in its expansion, this ‘realm of bodies’ to ‘realm of shapes’ is like a drop of water in an ocean.

Beyond ‘realm of shapes’ is the ‘realm of soul’. In its expansion, the ‘realm of shapes’ to the ‘realm of soul’ is like a ring in a large land. So, in order to understand, take ‘realm of shapes’ as a ‘burzakh’ (purgatory) in between the ‘realm of soul’ and ‘realm of bodies’ or take it as a veil.

Realm of soul is the first level of the divine reality. It is a collective level. All shapes and forms are contained in it. All shapes are vague (without specific gender, without full form). Contrary to this, in the realm of shapes, all shapes are present in detailed forms. But these shapes or forms are of very light density.
Page-32

So when the limited thoughts are purified i.e. when Nafs (self) and heart is purified, then the third eye is able to view the shapes of lighter density. It means that when the reflection of such shapes is put on the mirror of bound imagination, then the events of the future are seen and predictions can be made that a certain event can happen at a certain time. Its example is same as of Sun, clouds and earth. If clouds come in between the sun and the earth, then the sunlight cannot reach the earth. The clouds are the burzakh in between the sun and the earth. If clouds are not present, then the sunlight will come down and light the earth.

… To summarize, if the bound astral body is purified, then the lower density shapes and forms which are present in the realm of shapes, will en-light one’s heart and the seeker will then be able to see the future and will have the power to understand the divine knowledge and will have the power to observe.

Naimat Shah Wali was one of the greatest saints and a friend of Allah. For this reason, he was granted the knowledge of ‘unseen’.
Page-33

He used ‘May Beenam’ in the above-mentioned Qaseeda. The understanding of divine wisdom and power to observe starts in the realm of shapes i.e. realm of moot but his levels/stations are far higher than this. He had the access to the realm of jabroot and lahoot.

Maulana Jalal-ud-din Roomi r.a. Said:
When the mirror of your heart will be clean and purified Then you will witness all shapes through water or dust
Page-33 (continued)

108. I ignore the old tale and inform about the Second Era (of Indo-pak)
109. From the Mogul Family, conqueror the second, will rule the land of India. A brave Rule.
110. Luxury will enter into there hearts; riches around and they will loose [ignore] the Usmani (Ottoman) way.
Page-34

111. They will rule India, Bengal, Kashmir and the Bhopal State for 300 years.
112. Their Empire will have access (influence) even in km, Bulkh, Bokhara and Tehran. Then they will vanish and shall be forgotten.
113. In India and in Iran, 7 generations (of moguls) will rule and then will vanish and disappear from the scene.
114. 0 the one who is being addressed, you will not see the rule of Moguls beyond 300 years. They will vanish like the “people of the Kahaf’ [People of the Cave] (39)
115. Then will come the last Era of this world and the eagles of Sidra will be wasted by the hands of the death.
116. Those warriors, Rajas & Maharajas [rulers] will take drugs and will get stoned. And the Christians will enter in their realms by posing merchants.
117. They will loose their Kingship. Those who will come as guests will become the masters and will issue currency/coin of non-Indian rule.
Page-35

118. 0 the one being addressed, you will see the Christians on the throne of the Indian kings. They will arrest the Muslims by false claims and through wicked tricks.
119. You should know that their rule would be for 100 years. 0 friends, I have seen this secret.
120. Islam and Muslims will be surprised and unable to do anything. Bulkh, Bokhara, Tehran, Sind and all India as well.
121. Indians will read English Knowledge in schools and colleges. They will ignore and the Islamic knowledge.
122. Then will come a war in which Russians and Japanese will take part. Japanese will be the victors (40)
————————————————————————-
 

(39) Points(111-121): Mogals (Mughals) ruled India and some other nations for a long time and then their empire vanished. Their children were killed and the English invaders destroyed their families and virtues. British East India co. entered in India in the guise of traders. Slowly, they bribed the officials to get more and more access and power. Then they formed their own Castles and their own army and started invading different cities and states. Finally in 1857, they got hold of the throne of India. England ruled India for approx. 100 years. In those hundred years, the western knowledge replaced Indian sciences. Rajas/Maharajas ruled in more than 50 states. All of them lost their kingdom. – MC
(40) Russo-Japanese War (1904-05), a military conflict in which a victorious Japan forced Russia to abandon its expansionist policy in the Far East, becomes the first Asian power in modern times to defeat a European power. The Russo-Japanese War developed out of the rivalry between Russia and Japan for dominance in Korea and Manchuria.–MC
————————————————————————-

123. They will be like the kings in a Chess game. Both players expansion will be unbalanced [on weak foundations]. Mediators will negotiate truce.
124. They will agree and fix the borderlines, will stop the war but the Agreement will be hypocritical.
Page-36

125. Russians will rule the Koh-Kaaf (a mountain range); also Kawarzam and Khewa will be conquered.
126. Will gain access even to Egypt, Sudan, Bokhara, Kohistan, Lebanon, Karakh, and Constantinople.
127. They will conquer up to the Sea of Khazar, Gailan. Through wickedness they will gain access to China and to the throne of Iran.
128. There will be a King in Muslims called Abdul Hameed. Like Iranian Kings, he will be a just one.(41)
129. In support of Islam he will stand up and struggle. After him, will come average sultan.(42)
130. Christians will attack him from all the sides and will get access to his land using tricks and wickedness.
131. After Hameed, the Sultan shall be Shah Khamis (or Fifth with the same name or title). He will sit on the throne unexpectedly.(43)
Page-37

132. The Deniers will rule East and West. When this will come true. (44)
133. There will be a mass murder in the Jungle of Marv [or Maroo], people will be killed. They will conquer Turkish lands.
134. The Second largest mass murder will occur in that era. Apparently the deniers will be victorious.
135. Then at last, the friend of the Allah, the Conqueror, will take his sword out. (45)
136. A new Life will run into Muslims, They will have the upper hand and you will see the nation of Uthman (ottomans or usmani) rejoicing.
137. The Plague and famine will appear in the lands of India, so Muslims will the at many places.
138. An earthquake, like the quack of the judgment day will occur. The 2/3 of Japan will be destroyed.

———————————————————————-
(41) Ottoman Emperor Abdul Hamid II (1876-1909) – MC
(42) ‘Amiana’ is Original word used in qaseeda. It has several meanings. Common, normal, cheap, average. – MC
(43) Muhammad V or Mehmed V (1909-1918) – MC
(44) Point 132 onwards: Probably these events are yet to occur. – MC
(45) ‘Habeeb-Ullah’ is the original word use in Qaseeda. It means ‘friend of Allah’ – MC
————————————————————————
Page-38

139. Two persons with the name Ahmad will misguide a lot of people. They will interpret Al-Quran at will.(i.e. misinterpret) (46)
140. There will be a war for 4 years on Western continent (Europe). Aleph (inglistan i.e. England) will cunningly win the war against Geem (Germany).(47)
141. This will be the first Great War. Mass murder will take place. 10.3 million lives will be lost.
142. They will reach a truce agreement but this truce will not be a permanent one.
143. Both the parties will silently manufacture weapons. That is Geem (Germany) and Aleph (England) will prepare for war.
144. When Japan will fight against China, Christians will fight with each other.
145. His first attack will be on France. British and Italians will also be in the state of war.
Page-39

146. Thus the Second Great war will start after 21 years. This will be fierce and aggressive than the first
war. (48)
147. Indians will also aid in this war. They will be unaware of the fact that this aid will be useless.
148. Weapons equal to the effect of lightening and of mass destructions will be manufactured by the famous scientists of that era.
149. O the one who is addressed, if you are living in the east you’ll hear the talk of the west.(49) The voices from the unseen places will be heard.
150. Both the Alephs (Inglistan and America), Russia and China will join hands together and will attack Aleph (Italia), Geem (Germany) and Second Geem (Japan) (50)
151. This war will continue for about 6 years. Will be bitter than the salty water and will be like a jungle crowded with wild beasts.
152. After that Christians will leave India. But before doing so, they will sow the seeds of wickedness (malice).(51)
————————————————————————————–
(46) Mirza Ghulam Ahmad of Qadian (1835 -1908) and his eldest son Mirza Basheer-ud-Din Mahmood Ahmad (1889-1965). Mirza claimed to be Mujadid, Mahdi and Jesus. His son was his Second Khalifa (Successor). Both of them wrote many books and misinterpreted Al-Quran. – MC
****
Dr. Allama Iqbal also mentioned two false prophets in his book Javed Nama 
(1) Mirza Ghulam Ahmad Qadiani (1838) (2) Mirza Hussain Ali Baha Ullah (1817)
(Read 3rd stanza of Poem here Khatab Ba Javed. Its from Book Javed Nama.
****
(47) History: WWI (1914-1918)
(48) History: WWII (1939-1945)
(49) Telecommunication, Radio – MC
(50) In Persian and in Urdu language, Alphabet ‘I’ sometimes has the similar sound of Alphabet ‘Aleph or A’ and is written in this matter. Similarly ‘G or J’ has similar sound of ‘Alphabet Geem’. – MC
(51) Hatred in Hindus and Muslims. Unresolved status of Kashmir and some other areas etc. – MC
———————————————————————————–
Page-40

153. When this good news will spread, people from different places will get together at Bab-e-Aali *.
(*Bab-e-Aali may be a place in Lahore named now Bab-e-Pakistan near Walton Cantt, A place where biggest refugees camp was built in Lahore. Writer Mumtaz Mufti also mentioned this camp in his book Alakh Nagri)

154. India will be divided into two parts. Sadness and Sorrow will result from the cunning and deceit.(52)
155. Kings without crown will rule Indo-pak.(53) They will issue orders without knowledge. Statements will be ambiguous.
156. (Officials) will show laziness after taking bribes, they will knowingly ignore the issues. Will change the king’s orders.
157. Knowledgeable people will mourn and the wise will mourn over the knowledge and wisdom they have. Fools will be naked, busy dancing and listening songs.
158. Kind hearts will turn cold and respect will turn into boldness. All this will occur because of the evil of that time.
159. They will commit the crime of incest. Sister with brother, boy with his mother and father with his daughter.
Page-41

160. Sarkar Muhammad S.A.W.’s nation will commit such criminal and disgusting acts.
161. Evil and bad acts will spread everywhere. Even mother will cheat his daughter.
162. Those misled Muftis (clerics) will issue baseless decrees. Will try to twist the orders of Sharia (Islamic law)
163. Sinners will become the elders of their nation. So its house of wise will be deserted.
164. People in cities and in mountains, will fearlessly consume drinks in summer and will take drugs.
165. Like a candle, the orders of Islam will meltdown and vanish. Person with knowledge will be considered foolish and the people without knowledge will be revered.
166. Those scholars of the earth will be arrogant (proud). They will decorate their unclean face with high turbans.(54)
Page-42

167. Will decorate them by wearing high turbans and fancy robes. This is equal to hiding the golden calf of Samir the magician under their clothing. (55)
168. Muslims, in their weakness, will find reasons and logics for their wrong behaviors.
169. Will forget what is halal and what is haram.(56) Because of kidnappings and rapes, women loose their dignity and respect.

——————————————————————————
(52) India divided into India and Pakistan in 1947. A mass murder of Muslim immigrants took place. – MC
(53) Presidents, prime ministers – MC
(54) Wearing Turban was the sign of respected ones / elders. – MC
(55) Samir (Samari Jadugar) the Magician made a Golden Calf during the Prophet Moses’ (A.S.) seclusion. The Jews worshipped that idol. Samir’s calf is a sign of hypocrisy and a sign of disbelief in God! – MC
(56) Halal- allowed, haram-forbidden things and actions – MC
—————————————————————————–

170. Hatred will appear; women will be without veil, will look innocent but in reality, are prostitutes.
171. Some people will sell their daughters and act as pimps. Base and mean people will have attire of honored and pure ones.
172. Some people will not have any shame or respect for privacy. Mothers will compare themselves with their daughters.
173. Deniers will suggest Islam to Muslims. Stopping them from performing pilgrimage and stopping them to say their daily prayers.
Page-43

174. In India, like Satan, a man from Turkish lineage will tell big lies.
175. Judges will be at the height of foolishness; scholars with great knowledge will take bribes.
176. Good advices will vanish, and you’ll see that Governments will be formed through deceit and through lies.
177. Hypocrisy will spread in the east and in the west, in all four directions. Common people will accept the widespread evil and sins.
178. You’ll not see anyone defending the truth. They will honor the thieves and robbers.
179. Lies, hypocrisy, backbiting and all other sins will spread everywhere. Murders, adultery and homosexuality will spread at many places.
180. Sheikhs (teachers) will give satanic suggestions. They will sit in their homes with their lovers.
Page-44

181. Pious will obey Satan; scholars will be the enemies of God. Worshippers will forsake worship and saints will be hypocrites.
182. The customs and rituals of the Christians (57) will be adopted everywhere. Innovations (in religion and traditions) will spread. Sunnah of the Prophet (the way of the Prophet) will disappear.
183. If you give few coins of silver to a judge, he will change his decision like the dog of a hunter.
184. A group will take interest over the loans. May God damn such people, sitting on an enormous wealth.
185. Muslims will be ignoring their prayers. Will be the prisoners in the world of lust. This will happen in the world.
186. Fasting, prayers and obedience will disappear suddenly. Zikr and religious chants will be hypocritical.
187. Fondness of Prayers, fasting, Hajj, and Charity will decrease. Feel like a burden to their hearts.
Page-45

188. Suddenly Muslims will hear a noise.(58) They will fight fearlessly with the deniers.
—————————————————————————-
(57) It seems that to Naimat Shah, every westerner is a Christian. Amazingly accurate description of today’s world. The western culture, clothing, language, traditions etc. are spreading like a wild fire. Just look around in your countries. Another gift / curse of globalization to mankind. – MC
(58) History: According to Hafiz Nizami, this stanza refers to Indo-Pak war of 1965 in which Indians lost and finally agreed to Tashkent Declaration.
—————————————————————————-

189. Sword of success in hands, they will fight with the enemy until they win by the grace of Allah.
190. Hellish people will run away from the heart of Punjab (Khem Karan). Muslims will control the city.
191. All the deniers will reach an agreement of unity and they will defeat the Muslims by force.(59)
192. Hindu Banya (60) (money-Lender) will be the flag-bearer of India. Denier will pass away in his state of denial.
193. After the war of 17 days, after many sacrifices and fighting, the Ghazis will be successful.(61)
194. At the time of anxiety and depression, Allah will be merciful towards Muslims
Page-46

195. Muslims will force the leader to step down, after that Muslims will face a degrading defeat.(62)
196. With great sadness, I am advising you to refrain from the ways of the priests.
197. A great wrath will come upon those who deserve the punishment. Finally Allah will order a great punishment.
198. Muslims will loose their lives; loose their strength, through the hands of a Hindu nation carrying weapons.(63)
199. Eastern Part will be destroyed through the deception of the wicked. Western part will mourn over these cruel actions.
200. Lives of Muslims will be cheaper than property and the blood of Muslims will run like a deep ocean.
201. A big city will become a great slaughterhouse. Like Karbala, every house will experience great suffering.(64)
202. The Leader of Muslims will be the friend of the enemy.(65) He will help them by keeping his promise.
203. The one whose name’s first letter is ‘Ga’ and this name will have 6 letters; will surely be a victor through the cunning and wickedness.(66)
———————————————————————————

(59) Maybe a reference to Tashkent Declaration – MC

(60) Lal Bahadur Shastri (1904-1966), Third Prime minister of India. He passed away shortly after the defeat in the war – MC
(61) Indo-Pak was of 1965 lasted exactly 17 days. – MC
(62) President Ayub Khan, who fought the 1965 was, was forced to step down. Muslims lost eastern Province of Bengal in 1971. -MC
(63) A reference to Indian funded ‘Mukti-Bahni’ organization. This organization committed a genocide of Muslims in 1970-1971 – MC
(64) A reference to Dhaka. Now the capital of Bangladesh. – MC
(65) General yahya an, then president of Pakistan was a well-known traitor – MC
(66) Name was Gandhi. With 6 letters in both English and Urdu/Persian language. Indra Gandhi was the prime minister of India at the time of 1971 war – MC
——————————————————————————
Page-47

204. This incident will happen in between the two Eid festivals when the Sun will be at 50 degree and moon will be traveling through Sharteen. At that time, Hindu will win over the bad men (67)
205. Muslims will acquire weapons in the month of Muharram. They will take bold steps then.(68)
206. After that a revolt will appear in India. Chaos will spread in the land of deniers.
207. Idol-worshippers will then be cruel towards the Muslims. Muslims will stay patient in front of Hindu wrath and anger.
208. Muslims of western part will be blessed by God’s mercy and there will appear serious people.
209. Help will come from the Northeast part to pave the way for victory.
210. An army of warriors well versed with weaponry will come and add a great strength to Muslims.
 Page-48

211. Turkish, Arabs, Iranians and people of Middle East will come fast with the intentions to help.
212. People from mountains and forests will come too. A flood of fire in all directions.
213. Chitral (69), Nanga Parbat (70), Gilgat (71) near china, and Tibet (72) will become the war ground.
214. Turkish, Chinese and Iranians will unite together and they will conquer India.(73)
215. Like an army of ants, they will conquer India in no time. I sware by the Almighty Allah that Muslim nation will be the victor.
216. People of Kabul will come out to fight the deniers. The deniers will try to present excuses.
217. The earth will shake by the march of the Ghazis of Sarhad. To reach their goal, they will come fast.  

Page-49
218. The common people and the officials will get together. In his work, there will be hundred kinds of sorrows.(74)
————————————————————————————
(67) History: ‘Sheen’ stands for ‘Shams’ (Sun). ‘Noon’ is 50″ ‘ degree in astrological than. Sharteen is Moon’s first manzil in astrological than. Moon of the 2 day. This incident happened on November 22, 1971 when Yahya Khan was the President of Pakistan.

(68) In my opinion 204-onwards are the predictions of future war in India and Pakistan – and Allah knows best – MC
(69) A valley in northern areas of Pakistan – MC
(70) A mountain range in the northern area of Pakistan – MC
(71) A valley in northern Area – MC
(72) Tibet is part of china now a days – MC
(73) New alliances will be formed and this shall be the beginning of the WWIII. – And Allah knows best  – MC
(74) Referring to someone whose actions will result into many sad events – MC
———————————————————————————-
219. This event will take place after the Eid Qurban and before the Eid-ul-Fitr’s prayers. They will acquire back the lost territory, which will be occupied by the enemy.
220. 3 times, the river of Attock will run with the blood of the deniers.
221. Punjab, City of Lahore, State of Kashmir, Do-Aab (Ganga-Jamna rivers), city of Bijnor, will be captured by the Muslims.
222. Beautiful girls and lovely sweethearts will be among the spoils of war for the Mujahids.
223. After this, the deniers will fully loose the war. The brave army will be happy and shall be victorious.
224. This battle will last for around 6 months. By the grace of Almighty God, Muslims will be the victors.
225. By the grace of God, Muslims will be very happy. Such will be shower of the blessings of God.
Page-50

226. The people of bad intentions for faith and for the religion will have lost their lives. All the India will be cleansed from the Hindu rituals (traditions).
227. An earthquake like the quack of the judgment day will occur. This earthquake will be the wrath on Hind (India) and Sindh (a province of Pakistan).
228. Like India, the west too will have bad luck. The Third Great War will begin.
229. Out of Two Alephs (England and America), one Aleph will be destroyed. ‘Ra’ (Russia) will attack the Aleph of the west.
230. The defeated ‘Geem’ (Germany or Japan) will become equal to (or unite with) the ‘Ra'(Russia). Very dangerous, hellish weaponry of fire will be used.
231. ‘Ra’ (Russia) will be destroyed by the anger and wrath of ‘Seen’ (China). Russia will save itself from china by cunning tricks.
232. Aleph (75) shall be destroyed to an extent that not a single dot of it will remain. Only its name and description will remain in the history books.
Page-51

233. This is the divine punishment for them and they will be given the title of ‘criminals’. None will dare raise head like priests do.
234. These dishonest people ruined their lives. Finally they dwell in the hell.
235. Those secrets that I narrated, those pearls that have handed over, are like the divine certificates. I described them because Allah surely will help Muslims.
236. O the one being addressed, if you want Allah’s help then follow the sacred word and Allah’s friends.

——————————————————————
(75) According to Hafiz Nizami, Aleph stands for England – MC

——————————————————————

237. Until the best year
Approaches. Imam Mehdi R.A. The guided one will rise.

238. Suddenly, during the days of Hajj, Imam Mahdi r.a. Will appear. News of his appearance will spread in the world.
Page-52

239. After that the Denier Anti-Christ (Dajjal) will appear from the city of Asfahan. Prophet Isa (A.S.) (Jesus/Yesu/Yeshua) will return to destroy the antichrist.
240. 0 Naimat Shah, Be silent! Don’t reveal the secrets of Allah. I am describing these events in the year
(Year 548 A.H. ) 
-THE END-

(Page 52 – Page-55)
The knowledge of Walis
Unable to translate because the language used is too complex and the terms are old and obscure.
My knowledge of the spiritual realms and grip on this language is not enough to translate this passage.

(Page 56)
 Hafiz Muhammad Sarwar Nizami educated by Hazrat Amanat Ali Shah Chishti Nizami (R.A.) of Mughalpura Lahore, Pakistan.
Other details on this page, praising H.M Sarwar Nizami’s efforts to compile this book
-THE END OF THE BOOK-
 
Share this:

    Click to share on Facebook (Opens in new window)Click to share on Twitter (Opens in new window)Click to share on LinkedIn (Opens in new window)Click to share on Tumblr (Opens in new window)Click to share on WhatsApp (Opens in new window)Click to share on Telegram (Opens in new window)Click to share on Reddit (Opens in new window)Click to share on Skype (Opens in new window)Click to share on Pinterest (Opens in new window)Click to share on Pocket (Opens in new window)

Related

Saffron
September 28, 2016

Iran – “Wipe Saudi Arabia Out Of Existence”
September 29, 2016
With 1 comment

Kalagnanam
October 1, 2016
Posted in Uncategorized	
Post navigation
Previous postIran – “Wipe Saudi Arabia Out Of Existence”
Next postKalagnanam
Leave a Reply

    facebook twitter instagram 

* Orissa Jagannath Predictions  Bavisya-Malika

https://www.youtube.com/watch?v=cXOie84pffI
orisa pridiction
Odia literature was largely enriched by the contributions of the five saints (Panchasakha). They were Jagannath Das, Balaram Das, Achyutanda Das, Yasovanta Das and Sisu Ananta Das. Pancha Sakhas were the collective name for the famous five Saints or five Friends. Balaram Das, Jagannath Das, Achyutananda Das, Ananta Das, and Jasobanta Das were five saints who emerged in the sixteenth century. Shri Achyutananda Das was the most prolific writer of the Panchasakhas and has written numerous books classified under categories such as Pothi, Mālika, Tika, Gita etc.,

believed not in one life but in many successive lives. He is known as the Mahapurusha, which means - a great man. Jagannath Das, Balaram Das, Achyutanda Das, Yasovanta Das and Ananta Das. Jagannath Das and Shri Chaitanya were contemporaries. As per their narration, towards the end of Mahabharat when Lord Krishna was leaving his mortal body, Nilakantheswara Mahadeva appeared & told him that the Lord's companions Dama, Sudama, Srivatsa, Subala, and Subahu would reincarnate in the Kali-yuga & be known as Ananta, Acyutananda, Jagannatha, Balarama and Yasovanta, respectively. Mahapurusha Achyuta had established various spiritual energetic centers called Gadi. Panchasakhas are compared with Nostradamus for predicting future events. Kindly subscribe this channel, like the videos, share and put your valuable comments. 
* Sri Veerabrahmendra the Precursor of Kalki English book 
https://www.scribd.com/doc/49630026/Sri-Veerabrahmendra-the-Precursor-of-Kalki
* Kali-yugam Intro 
** how to create janma-kundali (birth chart and jatha-kam, lagna-kundali) : 
https://www.youtube.com/watch?v=1p-E5r5r16A
** Lunar Months(Masa):
| English Month     | Telugu Month | Telugu Pronunciation |
|-------------------+--------------+----------------------|
| March/April       | చైత్రము         | Chaithramu           |
| April/May         | వైశాఖము        | Vaisaakhamu          |
| May/June          | జ్యేష్ఠము        | Jyeshtta             |
| June/July         | ఆషాఢము      | Aashaadhamu          |
| July/August       | శ్రావణము       | Sraavanamu           |
| August/September  | భద్రపదము       | Bhaadhrapadamu       |
| September/October | ఆశ్వయుజము    | Aasveeyujamu         |
| October/November  | కార్తికము       | Kaarthikamu          |
| November/December | మార్గశిరము      | Maargaseershamu      |
| December/January  | పుష్యము       | Pushyamu             |
| January/February  | మాఘము       | Maakhamu             |
| February/March    | ఫాల్గుణము     | Phaalgunamu          |

** 60 year samvatsar cycles 
These 60 Samvatsaras repeats in a cycle of 12 years. The significator of the year is Shani, Saturn, which takes approximately 30 years to complete the entire twelve signs of the zodiac.
The yugas of periods began when both Jupiter and Saturn were at 0-degree of Aries. 
So, if we take the lowest common multiple between the motion of Jupiter and Saturn (approximately 12 years and 30 years), we get the count of 60.

Therefore, every 60 years, both Jupiter and Saturn reach the 0-degree of Aries, and this interplay between both the planets, the angles formed, the influences that arise due to the combination, significantly affect the Samvatsaras and the individuals.

The sixty Samvatsaras (Prabhava to Kshaya) are divided into three groups of 20 Samvatsaras,
-  first group of 20 Samvatsaras (Prabhava to Vyaya) is assigned to Lord Brahma, 
-  the next group of 20 Samvatsaras (Sarvajit to Parabhava) to Lord Vishnu, 
-  the last 20 (Plavanga to Kshaya) to Lord Shiva.

There is other difference in vedic calander based on 
earth wobble movement :earth axis or north-pole does not matches druva nakshatra and it complete once circle for every 26,000 years 

*** Names of samvatsaras
| S. No | Telugu Year Name | Falling Years          |
|-------+------------------+------------------------|
|     1 | Prabhava         | 1867, 1927, 1987, 2047 |
|     2 | Vibhava          | 1868, 1928, 1988, 2048 |
|     3 | Shukla           | 1869, 1929, 1989, 2049 |
|     4 | Pramodyutha      | 1870, 1930, 1990, 2050 |
|     5 | Prajothpathhi    | 1871, 1931, 1991, 2051 |
|     6 | Angeerasa        | 1872, 1932, 1992, 2052 |
|     7 | Shreemukha       | 1873, 1933, 1993, 2053 |
|     8 | Bhaava           | 1874, 1934, 1994, 2054 |
|     9 | Yuva             | 1875, 1935, 1995, 2055 |
|    10 | Dhatha           | 1876, 1936, 1996, 2056 |
|    11 | Eashwara         | 1877, 1937, 1997, 2057 |
|    12 | Bhahudhanya      | 1878, 1938, 1998, 2058 |
|    13 | Pramadi          | 1879, 1939, 1999, 2059 |
|    14 | Vikrama          | 1880, 1940, 2000, 2060 |
|    15 | Vrusha           | 1881, 1941, 2001, 2061 |
|    16 | Chitrabhanu      | 1882, 1942, 2002, 2062 |
|    17 | Swabhanu         | 1883, 1943, 2003, 2063 |
|    18 | Thaarana         | 1884, 1944, 2004, 2064 |
|    19 | Paarthiva        | 1885, 1945, 2005, 2065 |
|    20 | Vyaya            | 1886, 1946, 2006, 2066 |
|    21 | SarvaJithhu      | 1887, 1947, 2007, 2067 |
|    22 | Sarvadhaari      | 1888, 1948, 2008, 2068 |
|    23 | Virodhi          | 1889, 1949, 2009, 2069 |
|    24 | Vikruthi         | 1890, 1950, 2010, 2070 |
|    25 | Khara            | 1891, 1951, 2011, 2071 |
|    26 | Nandana          | 1892, 1952, 2012, 2072 |
|    27 | Vijaya           | 1893, 1953, 2013, 2073 |
|    28 | Yaja             | 1894, 1954, 2014, 2074 |
|    29 | Manmadha         | 1895, 1955, 2015, 2075 |
|    30 | Durmukhi         | 1896, 1956, 2016, 2076 |
|    31 | Hevalambhi       | 1897, 1957, 2017, 2077 |
|    32 | Vilambhi         | 1898, 1958, 2018, 2078 |
|    33 | Vikari           | 1899, 1959, 2019, 2079 |
|    34 | Sharvari         | 1900, 1960,2020, 2080  |
|    35 | Plava            | 1901, 1961, 2021, 2081 |
|    36 | Shubhakruthu     | 1902, 1962, 2022, 2082 |
|    37 | Shobhakruthu     | 1903, 1963, 2023, 2083 |
|    38 | Krodhi           | 1904, 1964, 2024,2084  |
|    39 | Vishvavasu       | 1905, 1965, 2025, 2085 |
|    40 | Parabhava        | 1906, 1966, 2026, 2086 |
|    41 | Plavanga         | 1907, 1967, 2027, 2087 |
|    42 | Keelaka          | 1908, 1968, 2028, 2088 |
|    43 | Sowmya           | 1909, 1969, 2029, 2089 |
|    44 | Sadharana        | 1910, 1970, 2030, 2090 |
|    45 | Virodhikruthu    | 1911, 1971, 2031, 2091 |
|    46 | Pareedhavi       | 1912, 1972, 2032, 2092 |
|    47 | Pramadeecha      | 1913, 1973, 2033, 2093 |
|    48 | Aananda          | 1914, 1974, 2034, 2094 |
|    49 | Rakshasa         | 1915, 1975, 2035, 2095 |
|    50 | Nala             | 1916, 1976, 2036, 2096 |
|    51 | Pingala          | 1917, 1977, 2037, 2097 |
|    52 | Kalayukthi       | 1918,1978, 2038, 2098  |
|    53 | Sidhharthi       | 1919, 1979, 2039, 2099 |
|    54 | Roudri           | 1920, 1980, 2040, 2100 |
|    55 | Durmathi         | 1921, 1981, 2041, 2101 |
|    56 | Dundubhi         | 1922, 1982, 2042, 2102 |
|    57 | Rudhirodhari     | 1923, 1983, 2043, 2103 |
|    58 | Rakthakshi       | 1924, 1984, 2044, 2104 |
|    59 | Krodhana         | 1925, 1985, 2045, 2105 |
|    60 | Akshaya          | 1926, 1986, 2046, 2106 |

*** Influence of samvatsar on birth
https://circleofdivineastrology.com/samvatsara-the-jupiter-years-you-are-the-year-you-are-born-in/

https://www.clickastro.com/blog/hindu-calendar-characteristics-of-people/


Indian Astrology
Samvatsaras: The Meaning & Its Importance in Vedic Astrology
Date: April 9, 2021 Author: Clickastro
hindu calendar
Lord Prajapati or Brahma is known to be the embodiment of Samvatsara that is widely used to explore a different segment of time like day, ritus (seasons), Ayana, and Month masa.

The term “Samvatsara” is a Sanskrit word for ‘year’ in the Vedic literature. It roughly means a period of one full year sidereal when the Sun enters the sign of Aries. Some astrologers define it as the time in which Brihaspati (planet Jupiter) with its average speed crosses the journey of one zodiac sign and moves on to the next. According to this definition, when Jupiter completes the entire circle of traversing all 12 zodiac signs, it comprises 12 Samvatsaras. During the entire journey, Jupiter is either close by or far from planet Earth based on which it creates positive or negative influences for an individual.

The Hindu calendar has a cycle of 60 years and is named from Prabhava to Kshaya. Generally, the new Hindu year begins at the end of April every year. In the current cycle, the year Prabhava coincides with the Christian year 1987.

indepth horoscope
These 60 Samvatsaras repeats in a cycle of 12 years. The significator of the year is Shani, Saturn, which takes approximately 30 years to complete the entire twelve signs of the zodiac. The yugas of periods began when both Jupiter and Saturn were at 0-degree of Aries. So, if we take the lowest common multiple between the motion of Jupiter and Saturn (approximately 12 years and 30 years), we get the count of 60.

Therefore, every 60 years, both Jupiter and Saturn reach the 0-degree of Aries, and this interplay between both the planets, the angles formed, the influences that arise due to the combination, significantly affect the Samvatsaras and the individuals.

Get your FREE Kundli with remedies

The sixty Samvatsaras (Prabhava to Kshaya) are divided into three groups of 20 Samvatsaras each wherein the first group of 20 Samvatsaras (Prabhava to Vyaya) is assigned to Lord Brahma, the next group of 20 Samvatsaras (Sarvajit to Parabhava) to Lord Vishnu, and the last 20 (Plavanga to Kshaya) to Lord Shiva.

Check Your Free Astrology Online

Samvatsara from 1900 AD to 2020 AD
A chart showing the Hindu years (Samvatsara) from the Christian era 1900 to 2020 is given below:

1900 	Sarvari 	1900 	Sarvari
1901 	Plava 	1901 	Plava
1902 	Subhakritu 	1902 	Subhakritu
1903 	Sobhakritu 	1903 	Sobhakritu
1904 	Krodhi 	1904 	Krodhi
1905 	Viswavasu 	1905 	Viswavasu
1906 	Parabhava 	1906 	Parabhava
1907 	Plavanga 	1907 	Plavanga
1908 	Keelaka 	1908 	Keelaka
1909 	Soumya  	1909 	Soumya 
1910 	Sadharana 	1910 	Sadharana
1911 	Virodhikritu 	1911 	Virodhikritu
1912 	Paridhavi 	1912 	Paridhavi
1913 	Pramodisha 	1913 	Pramodisha
1914 	Ananda 	1914 	Ananda
1915 	Rakshasa 	1915 	Rakshasa
1916 	Nala 	1916 	Nala
1917 	Pingala 	1917 	Pingala
1918 	Kalyukti 	1918 	Kalyukti
1919 	Saddhartha 	1919 	Saddhartha
1920 	Roudri 	1920 	Roudri
1921 	Durmathi 	1921 	Durmathi
1922 	Dundubhi 	1922 	Dundubhi
1923 	Rudhirodgari 	1923 	Rudhirodgari
1924 	Rakthkashi 	1924 	Rakthkashi
1925 	Krodhana 	1925 	Krodhana
1926 	Kshaya 	1926 	Kshaya
1927 	Prabhava 	1927 	Prabhava
1928 	Vibhava 	1928 	Vibhava
1929 	Sukla 	1929 	Sukla
1930 	Pramodhati 	1930 	Pramodhati
1931 	Prajothpati 	1931 	Prajothpati
1932 	Angirasa 	1932 	Angirasa
1933 	Srimukha 	1933 	Srimukha
1934 	Bhava 	1934 	Bhava
1935 	Yuva 	1935 	Yuva
1936 	Dhatu 	1936 	Dhatu
1937 	Eswara 	1937 	Eswara
1938 	Bahudanya 	1938 	Bahudanya
1939 	Pramadi 	1939 	Pramadi
1940 	Vikrama 	1940 	Vikrama
1941 	Vriksha 	1941 	Vriksha
1942 	Chitrabhanu 	1942 	Chitrabhanu
1943 	Swabhanu 	1943 	Swabhanu
1944 	Tharana 	1944 	Tharana
1945 	Parthiva 	1945 	Parthiva
1946 	Vyaya 	1946 	Vyaya
1947 	Sarvajitu 	1947 	Sarvajitu
1948 	Sarvadhari 	1948 	Sarvadhari
1949 	Virodhi 	1949 	Virodhi
1950 	Vikriti 	1950 	Vikriti
1951 	Khara 	1951 	Khara
1952 	Nandana 	1952 	Nandana
1953 	Vijaya 	1953 	Vijaya
1954 	Jaya 	1954 	Jaya
1955 	Manmatha 	1955 	Manmatha
1956 	Durmukhi 	1956 	Durmukhi
1957 	Hevimbi 	1957 	Hevimbi
1958 	Vilambi 	1958 	Vilambi
1959 	Vikari 	1959 	Vikari
The Samvatsara for this year is known as Sharvari (also called Zarvari or Sarvari). Each Samvatsara carries a particular essence that is correlated with its Sanskrit name along with its group ruler. The Samvatsara for this 2020-2021 year is the fourth in a group of five years ruled by the Manes.

career horoscope
The Manes are of two types: and are the children of Lord Brahma, also known as the Prajatis, who’re great rishis, progenitors, and protectors of the planet Earth, the animal kingdom, and the entire human race. Often called “Ancestors”, they inhabit their region between the realms of the human race (mankind) and the Gods, a place known as “Pitraloka”.

The word Sharvari means “night or twilight” or “pernicious or murderous” depending on the context with which we look at it. However, if we go by the ancestral predictions, this year is known to bring famine and trouble and that we are already seeing in the form of COVID-19 virus outbreak across the globe or in the form of locust plague spread out in parts of Africa. So, it won’t be wrong to say that the current five-year cycle ruled by the Manes (2017 – 2022) is challenging and a period of calamity for the human race.

Even in the last Sharvari cycle (during 1960) the human race experienced a similar case without the outbreak of the Great Chinese famine from 1959 – 1961.

Download Your Free Marriage Prediction

Influence of year of birth
No. 	Names of Divisions 	Explanation
1 	Prabhava 	A person born in this year will have a collection of precious things, have good children, and will live long and happy.
2 	Vibhava 	This person will be born rich and will be a person of artistic talents. They will become learned.
3 	Shukla 	The person born this year will be very handsome will enjoy good family life and will be of great character. 
4 	Pramodhati 	Those born in this year will be helpful, famous, and well-honored in life.
5 	Prajothpati 	Those born in this year will be honest, will help society, and will be respected by others.
6 	Angirasa 	The person born this year will be proud, enjoy good luck, and will have male children.
7 	Srimukha 	The person of this year will be very intelligent. They will learn many sciences and will be very successful in life.
8 	Bhava 	People born this year will enjoy a good life, earn fame, and will help others generously.
9 	Yuva 	The person of this year will have a brilliant countenance and will be successful and enjoy a long life.
10 	Dhathu 	Those born in this year will be successful in business enterprises, will be proficient in winning over enemies, and will not be spendthrift.
11 	Eswara 	Those born in this year will be short-tempered, proficient in many vocations, and will have a good personality.
12 	Bahudanya 	Those born in this year will be successful in military science and will be associated with vehicles.
13 	Pramadi 	Those born in this year will be successful in business and agriculture.
14 	Vikrama 	Those born in this year will achieve great success in life and will be courageous.
15 	Vriksha 	People born in this year will be slow in doing things, maybe lazy and will mostly serve others as servants.
16 	Chitrabhanu 	People born in this year will have high principles, enjoy great intelligence, and will be learned.
17 	Swabhanu 	Those born in this year will be liked by those in power and will be powerful, fearless and at times may commit bad deeds.
18 	Tharana 	Those born in this year will have a fickle mind. Bad deeds done by them may bring a bad name.
19 	Parthiva 	Those who are born this year will be lucky, will enjoy a good position in life, and will have for company powerful and influential people.
20 	Vyaya 	Those born in this year will be poor and may migrate from their home country to settle abroad.
21 	Sarvajitu 	Those born in this year are hard workers with many interests and possible success in sciences.
22 	Sarvadhari 	Those born in this year will have many servants, lead a life of luxury, and will enjoy life to the full.
23 	Virodhi 	Those born in this year will travel much and will face great opposition in life.
24 	Vikriti 	The person born in this year may be lean and dark in complexion with a defective limb and a heartless attitude at times.
25 	Khara 	The person born in this year will have lung trouble and will be passionate.
26 	Nandana 	Those born in this year will be happy and content.
27 	Vijaya 	The person born in this year will be learned and will have a highly logical mind and will be respected by others.
28 	Jaya 	The person born in this year will enjoy success and will be of great valor.
29 	Manmatha 	Those born in this year will be rich, enjoy female company, and will acquire precious articles.
30 	Durmukhi 	Those born in this year will be harmful, will keep company with women in the lower rungs of the society and have vulgar speech.
31 	Hevimbi 	The person born in this year will be rich, enjoy possessions, lead a comfortable life, and will have good character.
32 	Vilambi 	Those born in this year may tend to be greedy, lazy, and stingy.
33 	Vikari 	The person born in this year will be fickle-minded, unwise, suffer from false pride, and may do anything for self-gratification.
34 	Sarvari 	Those born in this year are passionate, sexually active, and incapable of doing anything on their own.
35 	Plava 	Those born in this year will be indecisive in their day-to-day life and may keep wandering from place to place.
36 	Subhakritu 	The person of this year is always a principled one bent on doing good to others. He will also learn many sciences and live long.
37 	Sobhakritu 	
** Visualistaion or grahical understanding of vedic-cosmology, vedic astrologi, and hindu-lunar calander using stal 
Geocentric Movement of the Solar System and the Hindu Solar Calendar https://www.youtube.com/watch?v=Q8T_ytDT280
Geocentric Movement of the Solar System and the Hindu Lunar Calendar https://www.youtube.com/watch?v=hnmfuTxgDa4
Moon phases from the ground and space https://www.youtube.com/watch?v=VfBreeZEDN4
Stellarium: Displaying and selecting constellations https://www.youtube.com/watch?v=kGe91uymh04 
Note : we can get vedic named stars from earth pint of view 

jyothisha  playlist : https://www.youtube.com/playlist?list=PLLZzwykvkseJ9ZTGLaXHEbW5eFEVgSfwF
Consist of How to calculate Tithis using nakshatra, 12 rasi, 12 masa  and calculate lunar masa, reason for adhika masa, what is uttarayana/dakshinayana , rtus, difference between druva nakshatra and nort-pole: wooble movement : advantage and disadvanges taking wobble effect on vedic date-time caluclation repeat cycle at 26,000 years    

27 nakshatra + 1 abhijit nakshatra 
12 rashis :
12 masa (lunar):
adhika masa : to match lunar-solar calander 
https://www.youtube.com/watch?v=cMTvzvMnsnQ&list=PLLZzwykvkseJ9ZTGLaXHEbW5eFEVgSfwF&index=4

Western Astrology :
Birth Chart: Identifying the Basic Components https://www.youtube.com/watch?v=-4vNK05bEjo

https://www.youtube.com/watch?v=dTxQ4o8a2MU
Vedic Astrology (Jyothisha Sastra)
Journey into Jyotisha Sastra with Shri. PVR Narasimha Rao 
Vedic Astrology Encyclopedia written by Father of Vasa (Parasar )  father of Jyotish Shastra or Vedic Astrology 
why parasar muni is know as father of Jyothish Sastra https://vedicfeed.com/maharishi-parashara/

download Epic-Brihat-Parasar-Hora-Shastram-Astrology(hindi)  https://www.dwarkadheeshvastu.com/Epic-Brihat-Parasar-Hora-Shastram-Astrology.aspx


Kundli kaise dekhe PART-65 "नक्षत्र" महा ज्योतिष की और पहला कदम || महा ज्योतिष विज्ञान || Astrology https://www.youtube.com/watch?v=ICPl-xIGWvI
Here abhijit nakastra is described and which place should we palace in nakastra-chat

** Rasi[12-zodica] and Nakshatra[27+ abhijit] 
nakshata (and 4 part know as pada) and rasi[zodiac] (affinity: air,water, fire,earth) https://www.youtube.com/watch?v=FA9C8YmMFlY
rasi : 12      angle : 360/12 = 90/3 = 30
Nakshatra: 27  angle : 360/27 = 40/3 = 13. 20' https://blog.indianastrologysoftware.com/nakshatras-in-astrology/
28th nakshata : abhijit 
gcp : 108
- 27*4=108
- So Each Nakastra is divided into pada consisting of 4 part and angle between each part angle= 360/108 = 10/3 = 3.20'
- 
each  nakshatra are dividied into 4 part is know as pada 

4 part of 1/108 will be nakshatra
9 part of 1/108 will be rasi 

Kundli kaise dekhe PART-65 "नक्षत्र" महा ज्योतिष की और पहला कदम || महा ज्योतिष विज्ञान || Astrology https://www.youtube.com/watch?v=ICPl-xIGWvI
Here abhijit nakastra is described and which place should we palace in nakastra-chat

jyothisa imp points 
http://www.hinduscriptures.com/vedic-sciences/nakshatra-vedic-astrology/2313/
* Estimate start of kali-yuga lord sri krihsna leaves earth =~ 3042BC
Kali-yuga, the Age of Quarrel, is a period of time lasting 432,000 year
Kalagnanam Visesha Vakyalu Devotional Album Lord Veera Brahmam Kalagnanam - https://www.youtube.com/watch?v=ijbhi-yiGcc

Before study we need to know little understand vedic cosmology and vedic astrology and jothisya sastra  need to know about 

kali Yuga started just over approx 5,000 years ago in 3102 and 3113 B.C.E BCE   when Krishna left our planet Earth which was calculated by famous scholars 
There are two estimation that is 0th Kali-yuga is either 
- 3042 BC or   
- 3102 BC. by aryabhada, astrologers
Present Kali yuga year is (3102BCE +2021AC= 5124 kaliyuga)  (3042 + 2021= 5063 kaliyuga)
Kali Yuga, the fourth age in a cycle, lasts for 
- 432,000 (human-solar) years 
- 1,200 divine years  (1 divine year = 360 solar (human) year or 6-cycles samvatsar

Kali-yuga consist of 3 parts 
- *Part-I* : *kali-yuga-sandhya* (dawn)       [3102BC-32,899CE]  36,000 solar year or   100 divine years
- *Part-II* : *kali-yuga*                   [32,899CE-392,899CE] 360,000 solar year or 1,000 divine years
- *Part-III* : *kali-yuga-sandhyams* (dusk) [392,899CE-428,899CE]  36,000 solar year or  1000 divine yearsa

Presently we are in part- I of kali yugam 
** Start of Kaliyuga by aryabhada ~= 3102 BC
- 3102 BC. by aryabhada, astrologers https://www.thegaudiyatreasuresofbengal.com/2021/04/11/beginning-date-of-kali-yuga-start/
Aryabhatta written that he was 23 years old when 3600 years of KaliYuga has passed. Since Aryabhatta born saka 398 or 476 AD, the starting of Kali-yuga ~ 3012BC
476 birth + 23 age = 499AC = 3600 AK
499 AC + Start_Kaliyuga = 3600
Start_Kaliyuga =~ 3101 BC

https://www.booksfact.com/puranas/kali-yuga-timeline-started-on-24-january-3102-bce.html

Sri Krishna was shot by an arrow of a hunter on his feet on the thursday evening of 23rd January 3102 BCE.
He left his physical body on 24th January 3102 BCE at 02 hours 27 minutes 30 seconds.
The next sunrise was on Friday, with moon in Aswini Nakshatra, tithi (lunar day) being Suddha Padyami (sukla pratipad or first day of lunar month) of Chaitra Maasam (lunar month) in Pramādi named year(13th of 60 year cycle).

If Kaliyuga is started in 1st year of 60-year cycle which is Prabhava    then   
Prabhava :  3113BC, 3053BC,  2993BC,  

** Start of Kaliyuga by indian independence <= 3053 BC
after 5000 years of kaliyuga
one lady will rule 14 years
ram ram ram will rule the india
prajal le raju i yeru
rajanu ane darmaha will be gone and pajanue ane darnaha : all kings will be gone and people will rule the country.
narasimha will rule the country (pv narasimha rao)

So we can understand that all this happend after independence 15th Aug 1947 so
1947 AD < 5000 AK
1947 + Start of Kaliyuga < 5000
Start of Kaliyuga  < 3053 BC 
** Estimate start of kaliyuga from kalagnana prophecies - Case 1:  Start of Kaliyuga < 3077BC
- In 5098  Kaliyuga to   price of rice is 2 grains per rupee  https://youtu.be/FD0VQ0Jo_NU?t=2304
  - Assume start of kaliyuga 3012BC or 3113BC then  
    - 5098 −3102= 1996 : if we assume that start of kaliyuga  is at 3102BC then  in 1996(5098 kaliyuga) price of rice should be Rs 1/  per 2 grains which is false according to data:
    - 5098 -3113=1985 : which is wrong estimate  then start of kaliyuga    
  - Assume in future price of rice is increase to 2grain per rupee
    - Estimate : 2021 + Start_Kaliyuga < 5098 then Start of Kaliyuga < 3077BC

- if assume there a 60 year life cycle difference then bc should be  estimate start of kaliyuga 3102 - 60 = 3042 BC
    - then 5098 kaliyuga will be (2056 + 3042)= 5098  which support  above prophecies
** Estimate start of kaliyuga from kalagnana prophecies - Case 2: Start of Kaliyuga < 3097BC
-  End of  5118 Kaliyuga year the entire world only 1/7 of population will be survied  https://www.youtube.com/embed/G68ngdKd7gU?start=766

Wrong Estimate  5118 -3102 = 2016 which didn't happen but it can happen in future
Estimate : 2021 + Start_Kaliyuga < 5118 then Start of Kaliyuga < 3097 BC

- If Start of Kaliyuga is 3102 -60 = 3042BC

Approximate : 5118-3042 = 2072 

** Estimate start of kaliyuga from kalagnana prophecies - Case III: Start of Kaliyuga < 3058 BC or ( 3058 -n*60) BC
- From Eashwara Naam Samvatsar to end of Vikrama Naam Samavatsaras  1 out of 7 villages and 1 out of 7 houses will survive  
  - Vikrama 	1880, 1940, 2000, 2060
- In  end of 5118 kaliyuga 1/7 world population will survive there is other prophecies
- (start of kaliyuga) + 2060 + n*60 <= 5118  = = > star of kaliyuga <= 3058 -n*60 BC
** Estimate start of kaliyuga from kalagnana prophecies - Case IV: Start of Kaliyuga < 3046- n*60 BC
- From Bhahudhanya Naam Samvatsaras : next 14 years there will be many catastopies seviour drouth and floods., bload bath,and seviour wars will happen, and many destructions will  occure.
  - Bhahudhanya 1878, 1938, 1998, 2058
  - Estimate (2058-2072)  
- End of 5118 of kaliyuga and 1/7 population survived
- For both prediction
  - Assume  after catastopies(2072AC) then at 5118 Kaliyuga world population will be 1/7  then
    2072+ n*60 + Start_Kaliyuga < 5118
    Start_Kaliyuga < 3046 -n*60 BC
-  start of kaliyuga 5118-2072 = 3046BC (which aprroximate over assuption but for perfect  match we need to see at 3046 BC is Prabhava nama samvatsar which is wrong)
  
- Assume that  kaliyuga start at 3042BC then 5118 kaliyuga (2076) then  which match that 3032BC is Prabhaba nama samvatsar 
   - From Estimate 2058-2072 pralays and war can happen
   - by 2076 world population will be 1/7 which satisfies both 
* EMACS vedic solar-lunar clander 
https://babbagefiles.blogspot.com/2010/12/hack-emacs-calendar-indiannepalihindu.html

https://www.gnu.org/software/emacs/manual/html_node/emacs/Sunrise_002fSunset.html
move to other calander like : Julian, HEBREWM ISLAMIC French Chinese calendar Persia Coptic Ethipic mayan calander 
https://www.gnu.org/software/emacs/manual/html_node/emacs/From-Other-Calendar.html

Phase of Moon https://www.gnu.org/software/emacs/manual/html_node/emacs/Lunar-Phases.html

source code of chinese-calendar.el https://github.com/hick/emacs-chinese/blob/master/chinese-calendar.el
http://web.mit.edu/Emacs/source/emacs-23.1/lisp/calendar/cal-china.el



how to activate chinese-calendar
* Python code 
https://stackoverflow.com/questions/6502966/calculating-lunar-lunisolar-holidays-in-python

How to Calculate the Phase of the Moon - Amy "SailorHG" Wibowo | JSConf Hawaii 2019 https://www.youtube.com/watch?v=JybbgAz3meQ

chinese cli :
https://raw.githubusercontent.com/wolfhong/LunarCalendar/master/generate.html


Astroniz : nasa database + nasa methods 
https://www.youtube.com/channel/UCvuCPVj5zTjxdR-EcatFfUg/videos


Simulating a real solar system with 70 lines of Python code : https://medium.com/analytics-vidhya/simulating-the-solar-system-with-under-100-lines-of-python-code-5c53b3039fc6

Visual Python Planetary Orbits https://www.youtube.com/watch?v=iHy2cB-jIaQ&t=332s
Vpython can be used for show or present 3d solar planaotry motion 
https://www.youtube.com/playlist?list=PLdCdV2GBGyXOnMaPS1BgO7IOU_00ApuMo


Kundli kaise dekhe PART-65 "नक्षत्र" महा ज्योतिष की और पहला कदम || महा ज्योतिष विज्ञान || Astrology https://www.youtube.com/watch?v=ICPl-xIGWvI
Here abhijit nakastra is described and which place should we palace in nakastra-chat
* Kalagnana
https://archive.org/details/KalagnanamBookTeluguTotal

Kalagnanam was written in Telugu Language and ‘Sandra Sindhu Veda’ on palm leaves, and Sri Veera Brahmendra Swamy’s sayings and ballads are being sung by wandering minstrels and mendicants. 
They are in the oral tradition. Most of his predictions have come true and rest is yet to come true. 
It is stated that Kalagnanam of the entire World contains 3,32,000 volumes. 
- A small part of Kalagnanam is available in Brahmamgari Matham at Kandimallayapalle, Siddhayyagari Matham at Mudumala, Rangarajugari Matham at Nagaripadu, 
- and the remaining major part is kept in the inner pit of Banaganapalle Mutt under tamarind sprout which has grown into a big tree now. 

Sri Veera Brahmendra Swamy wrote in his Kalagnanam that he was incarnation of Lord Vishnu and 
- would come again as Lord Kalki/Lord Veera Bhoga Vasantha Raaya to restore dharma and peace on the earth.
-  And devotees believe that he would rescue them whenever they plead him; 
- and he will come out from the Jeeva Samadhi when the blood of thousands of people, who beheaded with frustration when the calamities reach peak stage, touches his Jeeva Samadhi. 
- ( It may be noted that like Lord Rama came to earth when Lord Parasurama is still in existence, Lord Veera Bhoga Vasantha Raaya came to earth while both Lord Parasurama and Lord Veera Brahmendra Swamy are still on the earth. )
- ( The date of Sri Veera Brahmendra Swamy’s coming out from Jeeva Samadhi and of Lord Kalki/LordVeera Bhoga Vasantha Raaya is different).

Samvatsaras: The Meaning & Its Importance in Vedic Astrology
https://www.clickastro.com/blog/hindu-calendar-characteristics-of-people/

Telugu or local calander : https://sakalam.org/telugu-year-names-english/


https://www.youtube.com/embed/FD0VQ0Jo_NU?start=2265
bagaladesh : people will sink and disintegrate in water. (either floods or rise in ocean leve) most probabiliy floods
if by rise in ocena level

15 METER rise in sea level 50% bangalesh will submerge
36 METER rise in sea level 90% bangalesh will submerge 
For rise in sea leavel of bangalesh:  https://www.youtube.com/watch?v=DTQezhxW1Q4&list=PL8GN8IgGxgFEpCl3uzyOd7cvk24ubBNqn&index=78
But estimation show in 2100 there is only 2-3 meter rise in sea level 

Note : at 95meters rise in sea level total bangalesh will submerge
Note : at 95 meter rise in sea level in pakistan : https://www.youtube.com/embed/kEnNrhPNQOs?start=53
https://oceanservice.noaa.gov/hazards/sealevelrise/sealevelrise-tech-report.html
https://www.climate.gov/news-features/understanding-climate/climate-change-global-sea-level

Due to  floods lot of cites will be
Nellor will be submerged in water https://www.youtube.com/embed/Lyx-O7H8Syw?start=756 
Vijaywada : will not be submerged
Because on Vijay nama samvatvara lord veera boga will come and marry for this year he start to rule entire planet

but it is 12m above sea level so : we can say bangalesh will sumberge not because of rise in sea level but due to floods
https://www.youtube.com/watch?v=fEceoXBPSBU&list=PL8GN8IgGxgFEpCl3uzyOd7cvk24ubBNqn&index=66


World War :  https://www.youtube.com/embed/Lyx-O7H8Syw?start=976
in one month in adjust years 4 grahanamlu(sloar eclips or lunar eclipes) then in north india there will be earthquake


* Prediction Time-Line
- 2035: bramarammbha tala-paralu will be taken from the tree.
- 2036-38 : one great person will be born
- 2047-2065 : there will be many pralay's happening there after will be blood rivers and wars will happen all over the world world-war-3
  - https://www.youtube.com/embed/Lyx-O7H8Syw?start=1033
    In between Prabhava, Paarthiva  there will be many pralay's happening there after will be blood rivers and wars will happen all over the world
- 2047 2065 : There may be 3rd world war dure this thime
  Prabhava 	1867, 1927, 1987, 2047
  Paarthiva     1885, 1945, 2005, 2065
  1945:world war ii
  2005: sunami
  
- 2050-2056 i will reincarnate as veera boga vasanta rayulu(at 2073 Vijay Nama samvatsar (24 year old) marry at vijayawada and rule the world)
- 2057: will be very heat souring solar eclipes
- 2053: size of india will be reduced
- 2052: tamil there will be natural catastopies mubail, kolkata,cheenai, kakinada there willbe some dangerou
- 2050-2065 : All nation leaders will do war and may will die
  - In between Dhatha Naam Samvatsaras and Paarthiva Naam Samvatsaras all national leaders will do the war and many will be died.
    https://www.youtube.com/embed/VwGOH_c4OfQ?start=647
    Dhatha Naam Samvatsaras :  1876, 1936, 1996, 2050
    Paarthiva Naam Samvatsaras: 1885, 1945, 2005, 2065
- 2054: During (July-Aug) 2054 there will be heavy rise of wate in rivers many village and cites will be in water
  https://youtu.be/FD0VQ0Jo_NU?t=2415
  Bhaava Nama  Sraavana masa(July/August) due to heavy rise of water in rivers  many village and cites will be in water
  Bhaava 	1874, 1934, 1994, 2054
- 2054-2055 : Different states there will be seviour  ativrushti and anavrushti ( flood  drought)  and many Pralaya will happen
  - https://www.youtube.com/embed/VwGOH_c4OfQ?start=692
    In between bhaava and yuva nama samavtara in different states ther will be seviour ativrushti and anavrushti ( flood  drought)  and many Pralaya will happen
    Bhaava 	1874, 1934, 1994, 2054
    Yuva  	1875, 1935, 1995, 2055
- 2056 : During (Feb-Mar) 2057 Wednesday  18 cites will be destroyed
  - https://www.youtube.com/embed/VwGOH_c4OfQ?start=501
    Dhatha Naam Samvatsaras maga sudha Budhavāraṁ 18 town(cities) will destroy
    Magh month or Magha masam is the 11 th month in Hindu calendar (February- March ) Budhavāraṁ(Wednesday)
    Dhatha 	1876, 1936, 1996, 2056
- 2056: In Telugu State price of rice will be  increase for 1Rs is 2 grain
  https://youtu.be/FD0VQ0Jo_NU?t=2304
  In 5098  Kaliyuga Dhatha Mārgaśira(August/September) to Eashwara  Māgha māsaṁ (January/February)
  - Golkonda, Vinukonda, Kondavedu, thadipatri, guthi, balari, nellore, mangalagiri, munimadugu, ethamukala, gunturu, Bezawada(Vijayawada),kamam, kurnool, markapuram, tanjauru, puspagiri, mysore, chenapatanam
  - In these palace for  Rs 1/- price for rice is  2 grains(seeds) (price of rice will increase)
- 2058 :  25 Mega(Mahā) cites due to blood-bath will we destroied
  - https://youtu.be/FD0VQ0Jo_NU?t=2428
    Bhahudhanya Naam Samvatsaras 25 Mega(Mahā) cites due to blood-bath will we destroied
    Bhahudhanya 	1878, 1938, 1998, 2058
- 2058-2060 :There will be many many serious war and many will die
  - https://www.youtube.com/embed/VwGOH_c4OfQ?start=672
    Between Bhahudhanya Naam Samvatsaras and Vikrama Naam Samavatsaras there will be many many serious war and many will die
    Bhahudhanya	1878, 1938, 1998, 2058
    Vikrama 	1880, 1940, 2000, 2060
- 2058-2074 : From 2058 next 14 years there will be {many catastopies,seviour drouth and floods,bload bath,and seviour wars will happen,destructions} will  occure.
  - https://www.youtube.com/embed/VwGOH_c4OfQ?start=501
    From Bhahudhanya Naam Samvatsaras : next 14 years there will be many catastopies seviour drouth and floods., bload bath,and seviour wars will happen, and many destructions will  occure.
    Bhahudhanya 	1878, 1938, 1998, 2058
- 2058: At end of 2059 all caste will become one,rice, poor will be removed, people will eat leaves, sexually transmitted disease will increase
  - https://www.youtube.com/embed/VwGOH_c4OfQ?start=714
    At the end of  Bhahudhanya Naam Samvatsaras:	1878, 1938, 1998, 2058
    - all jati(race,tribe, X[may not be caste(కులం) ]) will become one.
    - the difference between rice, poor will be removed.
    - In Palnati seema (Palnadu: Costal Andhra) there will many Conflicts
    - Palnati people will eat leaves
    - In Siddipet due to war lot of muslims will die.
    - men will rome with out and mustaces  
    - For devotees, slaves, yogis there will be scarsity for shealter in the place 
    - In konaseema  conflicts will be born.
    - సుఖవ్యాధి(sexually transmitted disease) will prevail (increase drastically)
- 2059 :  due to vomiting and xxxxxx many people will die.
  - https://www.youtube.com/embed/VwGOH_c4OfQ?start=765
    In Pramadi Naam Samvatsaras due to vomiting and xxxxxx many people will die.
    Pramadi 	1879, 1939, 1999, 2059
- 2057-2060 :  1 out of 7 villages and 1 out of 7 houses will survive
  - https://www.youtube.com/watch?v=FD0VQ0Jo_NU&t=2445s
    From Eashwara Naam Samvatsar to end of Vikrama Naam Samavatsaras  1 out of 7 villages and 1 out of 7 houses will survive  
    - Vikrama 	1880, 1940, 2000, 2060
      Eashwara 	1877, 1937, 1997, 2057
- 2058-2072 : Srisailam Malikarjuna will dance village to village and sinfull people start to fear, and he will talk with people, may will die, rain of weapons will fall and many will die
  - https://youtu.be/FD0VQ0Jo_NU?t=3075
    From Bhahudhanya  to Nanadana  nama samvatsar :(2058-2072)
    In srisailam  malikarjura temple smoke file will start and temple shikaram will be on fire and and fall on ground
    - Inside temple deitys will come life and dance from village to village then sinfull people start to fear.
    - Lord Malikarjura will start to talk with people due to some people will die
    - Due to rain of weapons many will die
- 2058: In banagaupally 5 years old nagaiya boy will read vedas without any one teaching him vedas then tiger will come to banagaupally and black face vanagrudu (half monkey and half man) will cicle around the village and leave
  https://youtu.be/FD0VQ0Jo_NU?t=3541
  Bhahudhanya Naam Samvatsaras  in banagaupally 5 years old nagaiya boy will read vedas without any one teaching him vedas then tiger will come to banagaupally and black face vanagrudu (half monkey and half man) will cicle around the village and leave
  Bhahudhanya 	1878, 1938, 1998, 2058
- 2065: end of all national war's   
- 2065: world war 1/3 will survive
- 2071-2072 : all water will dry
  - https://youtu.be/FD0VQ0Jo_NU?t=5171
    From pashu nama samvatsar to  nandana nama samavatsara all water will dry
    Khara 	1891, 1951, 2011, 2071
    Nandana 	1892, 1952, 2012, 2072
- 2071 : Glories of kalki will be know entire world: village and cites blood rain will fall
  https://www.youtube.com/watch?v=FD0VQ0Jo_NU&t=4924s
  In khara nama samvatsar the Glories (Mahimalu) of me(sriman naranaya) will be know and entire world village and cites blood rain will fall
  Khara 	1891, 1951, 2011, 2071  
- 2072: Lot of stars(commets) will fall due to which earth will shake
  - https://www.youtube.com/embed/G68ngdKd7gU?start=654
    In nandana Naam Samavatsaras lot of stars(commets) will fall due to which earth will shake
    Nandana 	1892, 1952, 2012, 2072
    Estimate : 2072
- 2073 : 17th Moon Phase day, Ashada() Month 2073 : Kaliki will give darshan and start his rule the kingdom  rightous  before that 1/7 of sinfull people will be perished.
  - https://www.youtube.com/embed/G68ngdKd7gU?start=810
    In Vijaya Naam Samavatsara  Ashada Masa Śud'dha_Sapthami(17th Moon phase) i will give darshan to devotees and start dharma paripalana(Daramic Rule) before that 1/7 of sinfull people will be perished.
- 2073-3181 :  kaliki(24th year age) will come with rishi, yogi, sidhis, avadhuda, paramahamsa's and will marriage matru-vamsham vijayawada-girl and  rule 108 years after my descandace will rule  1000 year, during which all other religion will be perished and only sanatha-darma will prevail
  - https://youtu.be/FD0VQ0Jo_NU?t=5926
    vijaya naama samvatsara  kaliki will marriage matru-vamsham vijayawada-girl and will come with rishi, yogi, sidhis, avadhuda, paramahamsa's and rule 108 years after my descandace will rule  1000 year
    - Vijaya 	1893, 1953, 2013, 2073
- 2076 (5118 AK = 2076 + 3042 BC) : 1/7 world population will survive there is other prophecies
  - In  end of 5118 kaliyuga 1/7 world population will survive there is other prophecies
    - (start of kaliyuga) + 2060 <= 5118  = = > star of kaliyuga <= 3058 BC
- 2076 : End of  5118 Kaliyuga year(2076 + 3042)  in the entire world only 1/7 of population will be survied
  - https://www.youtube.com/embed/G68ngdKd7gU?start=766
    Oh Great people at the end of  5118 Kaliyuga year  in the entire world only 1/7 of population will be survied
    - Estimate (5118 -3042 = 2076, 5118 -3102 = 2016, 5118- 3058 = 2060)
    - Estimate time 2060, 2076 (1/7th population survive)
- 2076 : For 1 Pōka cekka (areca nut or beetel nut) you will get hand full of rice (పుట్టెడు బియ్యం).
  - https://www.youtube.com/embed/VwGOH_c4OfQ?start=1664
    After 5118 Kaliyuga year (2076)  before Aananda Naam Samvatsaras (2094): For 1 Pōka cekka (areca nut or beetel nut) you will get hand full of rice (పుట్టెడు బియ్యం).
    Meaning
    - In between  2076 and 2094 due to war, famine, dought, flood there will be a seviour shotage of food
    - due to war lot of people will die (only 1/7 of world population will be alive) less demand for rice so  price of rice can be fall down  
    - there will be huge agriculture developement 
    - and over-rice production will occure due (less demand and high supply) the cost of rice will be reduced very low  and they will sell one hand full of rice for 1 beetel-nut(Rs 1)
    - (5118 -30042 = 2076, 5118 -3102 = 2016)
    - Aananda 	1914, 1974, 2034, 2094
    - Estimated period 2016-2034 or  2076-2094
- 2076-2100 : 4th day wax/waning phase,Kaarthika (Oct-Nov) Month form this day sinful person will be suppressed and From 2100 Maha pralay will start
  - https://www.youtube.com/watch?v=FD0VQ0Jo_NU&t=5900s
    From Durmukhi Naama Samvatsara  Kaarthika sudha chaturthi  start with  suppressing sinful person  and goes to maha pralays:This  pralays will start at Roudri Naama Samvatsara Kaarthika masa 
    - Kaarthika masa : October/November
    - is the fourth day (Tithi) of both waxing and waning phase 
    - Durmukhi 	1896, 1956, 2016, 2076
    - Roudri 	1920, 1980, 2040, 2100
    - Estimate : 2076-2100  because supressing sinful person can't happen after 2016 (present timeline : because in future  adharma should increase war should happen  so it will happen after after 2076(5118 AK ) )
- ------------------------------------------------------------------------------------------------      
- 2024-25-or-2084-2085  (Krodi ) : India will participate in a war and the Indian Capital New Delhi will be bombed, in the year Krodhi (2024-25) the capital will be shifted from New Delhi to Anegondi (Near Hampi, Karnataka State). And in the same year i.e. Krodhi (2024-25), the Nellore region will be submerged.
  - India will participate in a war and the Indian Capital New Delhi will be bombed, in the year Krodhi (2024-25) the capital will be shifted from New Delhi to Anegondi (Near Hampi, Karnataka State). And in the same year i.e. Krodhi (2024-25), the Nellore region will be submerged. =source: https://laxmimadhav.wordpress.com/2016/10/01/kalagnanam/=
  - Hampi(Karnataka) may probably be destroyed by Nuclear Attack. =source: https://laxmimadhav.wordpress.com/2016/10/01/kalagnanam/=
  - Aurvedic medicin will discoved and be used to treate the nuclear attack   
  - A direct Disciple of Lord Parasurama and Acharya Nagarjuna, Sri Sanaari Visweswara and other Sidhdha Purushas (probably Aghori sect), with his Alchemy will clear the debts of the Country and save from financial difficulties, and later link all the rivers and save from severe drought. =source: https://laxmimadhav.wordpress.com/2016/10/01/kalagnanam/=   
- 2027or2087 :  there will be elicpes where sun will be visible is shape of a ring
  - https://youtu.be/FD0VQ0Jo_NU?t=3643
    In plavanga naama samvatsaram there will be elicpes where sun will be visible is shape of a ring
    Plavanga 	1907, 1967, 2027, 2087
- 2034-or-2094 : aṣṭami mārgaśir(Nov-Dec) Month, Thursday =Lord  malikarjura with goddess bramarammbha will come vindya mountain=
  - https://youtu.be/FD0VQ0Jo_NU?t=5888
    Aananda Naam Samvatsaras mārgaśira  bhalual asthami  guruvāraṁ srisailam Lord  malikarjura with goddess bramarammbha will come vindya mountain
    mārgaśir: (November/December 9th month in hindu)
    aṣṭami  : eighth day after the new or full moon
    guruvāraṁ : Thursday
    Aananda 	1914, 1974, 2034, 2094
- 2037-2038 or 2097-2098 : Ghōramaina(Horrible, dreadful, terrible) will start and it will continous till 2038-or-2098 in (uttara desham )[approximate: north india or  uttar pradesh or  nothen country]
  - https://www.youtube.com/embed/G68ngdKd7gU?star=666
    In Pingala Naam Samavatsaras Ghōramaina(Horrible, dreadful, terrible) will start and it will continous till Kalayukthi Naam Samavatsaras in (uttara desham )[approximate: north india or  uttar pradesh or  nothen country]
    Pingala 	1917, 1977, 2037, 2097
    Kalayukthi 	1918,1978, 2038, 2098


* Prediction of Kalagnana
- 2047 2065 : There may be 3rd world war dure this thime
  Prabhava 	1867, 1927, 1987, 2047
  Paarthiva     1885, 1945, 2005, 2065

  1945:world war ii
  2005: sunami
  2065: world war 1/3 will survive






when saturn enter methuna rashi there will be war and natural catuastropies (https://www.youtube.com/watch?v=z7UjN6xPrFI) next entry is on 2034
duration fo satrun in satrun  in each zodiac sign(rasi) is 2.5 years 
1913: world war 1
1943: world war 2
1973: bangalesh 1971 war(10 laks die),1973 china drought 3 lakhs has died  
2003-2005: earthquake iraq, 2004-5 indonesia sunami, 2005 kashmir earthquake   
2033: ?
2063:


https://www.youtube.com/embed/VwGOH_c4OfQ?start=647 
In between Dhatha Naam Samvatsaras and Paarthiva Naam Samvatsaras all national leaders will do the war and many will be died.
Dhatha Naam Samvatsaras :  1876, 1936, 1996, 2050
Paarthiva Naam Samvatsaras: 1885, 1945, 2005, 2065
 
https://www.youtube.com/embed/Lyx-O7H8Syw?start=1033
In between Prabhava, Paarthiva  there will be many pralay's happening there after will be blood rivers and wars will happen all over the world
- in between prabhaba and paarthiva =  bhahudany will come   
there is chance of occuring world war -3 
(1987-2005) or (2047-2065) + n.60 :


Prabhava 	1867, 1927, 1987, 2047
Paarthiva     1885, 1945, 2005, 2065   	

1945:world war ii
2005: sunami
2065: world war 1/3 will survive


when saturn enter methuna rashi there will be war and natural catuastropies (https://www.youtube.com/watch?v=z7UjN6xPrFI) next entry is on 2034


War- I   1914-1918   40 million: estimates range from around 15 to 22 million deaths and about 23 million 
War - II 1939-1945   70–85 million  
Estimate : 
Pralay : 1987-2005 :
war-III  2058-2065



may be world war II (1936-1945)

https://www.youtube.com/embed/VwGOH_c4OfQ?start=692
In between bhaava and yuva nama samavtara in different states ther will be seviour ativrushti and anavrushti ( flood  drought)  and many Pralaya will happen
Bhaava 	1874, 1934, 1994, 2054
Yuva  	1875, 1935, 1995, 2055


Note : Importance of bhahudnaya
https://www.youtube.com/embed/VwGOH_c4OfQ?start=501 

From Bhahudhanya Naam Samvatsaras : next 14 years there will be many catastopies seviour drouth and floods., bload bath,and seviour wars will happen, and many destructions will  occure.
- Estimate (2058-2072)  as end of 5118 (2074 + 3044BC) there will be only 1/7 survive
Bhahudhanya 	1878, 1938, 1998, 2058
Dhatha 	1876, 1936, 1996, 2056

Dhatha Naam Samvatsaras maga sudha Budhavāraṁ 18 town(cities) will destroy 
Magh month or Magha masam is the 11 th month in Hindu calendar (February- March ) Budhavāraṁ(Wednesday) 
Dhatha 	1876, 1936, 1996, 2056


https://youtu.be/FD0VQ0Jo_NU?t=2428
Bhahudhanya Naam Samvatsaras 25 Mega(Mahā) cites due to blood-bath will we destroied
Bhahudhanya 	1878, 1938, 1998, 2058




https://www.youtube.com/embed/VwGOH_c4OfQ?start=672
Between Bhahudhanya Naam Samvatsaras and Vikrama Naam Samavatsaras there will be many many serious war and many will die 
Bhahudhanya	1878, 1938, 1998, 2058
Vikrama 	1880, 1940, 2000, 2060

may be world war II (1938-1945)

https://www.youtube.com/embed/VwGOH_c4OfQ?start=714
At the end of  Bhahudhanya Naam Samvatsaras:
Bhahudhanya	1878, 1938, 1998, 2058 
- all jati(race,tribe, X[may not be caste(కులం) ]) will become one. 
- the difference between rice, poor will be removed.
- In Palnati seema (Palnadu: Costal Andhra) there will many Conflicts
- Palnati people will eat leaves
- In Siddipet due to war lot of muslims will die.
- men will rome with out and mustaces  
- For devotees, slaves, yogis there will be scarsity for shealter in the place 
- In konaseema  conflicts will be born.
- సుఖవ్యాధి(sexually transmitted disease) will prevail (increase drastically)
- Bhahudhanya	1878, 1938, 1998, 2058




https://www.youtube.com/embed/VwGOH_c4OfQ?start=765
In Pramadi Naam Samvatsaras due to vomiting and xxxxxx many people will die. 
Pramadi 	1879, 1939, 1999, 2059



Great ness of veera boga vasanta rayulu:

In mysore (Chamundeshwari or Durga) will to the dance and kill all mayavadhi's
kin's , brother, famil relationship will vanish
mala madhigalu will be come landlords https://www.youtube.com/embed/VwGOH_c4OfQ?start=885

nastika(atheist=non-beivers of god) will be perished.
astika (theist=belivers of god) will be respected.

https://www.youtube.com/embed/VwGOH_c4OfQ?start=1015  
There will be a country (desham)  born which is know as america and there will be many earthquake  will ocure 
 

In kashi where will be floods due to which thousands of village will be destroied
In trivani sagnamam due to floods 10,024 house(house) will be destroyed.

https://youtu.be/FD0VQ0Jo_NU?t=1977
kashi desam kalahalu(conflicts) palu avenu 


https://www.youtube.com/embed/VwGOH_c4OfQ?start=1040
In turkey due to huge cyclon lots of peopl will die 
To turaka desam kali will be send

https://www.youtube.com/embed/VwGOH_c4OfQ?start=1045  
Bhadrapada Masa(6th month of Hindu calendar  September 7 to October 6.) In Madhya dēśaṁ ( madhya pradesh or middle east arabic country)  there will be an earthquake at 4 am due to which 48 village will be destroy 

Korukonda  Vizianagaram hanuman due to (Āgrahaṁ=Anger, choler, rage, wrath) will increase his size)
"Orugallu" or  Warangal national treasure will be realived.


https://www.youtube.com/embed/VwGOH_c4OfQ?start=1113
Patala-ganga: under-water ground will be dried and from ground fire will be rise 


Draviḍa dēśaṁ dagdhaṁ(will burned


https://youtu.be/FD0VQ0Jo_NU?t=2415
Bhaava Nama  Sraavana masa(July/August) due to heavy rise of water in rivers  many village and cites will be in water 
Bhaava 	1874, 1934, 1994, 2054


https://youtu.be/FD0VQ0Jo_NU?t=2304
In 5098  Kaliyuga Dhatha Mārgaśira(August/September) to Eashwara  Māgha māsaṁ (January/February) 
- Golkonda, Vinukonda, Kondavedu, thadipatri, guthi, balari, nellore, mangalagiri, munimadugu, ethamukala, gunturu, Bezawada(Vijayawada),kamam, kurnool, markapuram, tanjauru, puspagiri, mysore, chenapatanam 
- In these palace for  Rs 1/- price for rice is  2 grains(seeds) (price of rice will increase)
- Estimate start of kaliyuga from kalagnana prophecies: 


- In 5098  Kaliyuga to   price of rice is 2 grains per rupee 
  - (5098 −3000 = 2098 : rougf estimate so  
  - Assume start of kaliyuga 3012BC then  
    - 5098 −3102= 1996 : if we assume that start of kaliyuga  is at 3102BC then  in 1996(5098 kaliyuga) price of rice should be Rs 1/  per 2 grains which is false 
  - if assume there a 60 year life cycle difference then bc should be  estimate start of kaliyuga 3102 - 60 = 3042 BC
    - then 5098 kaliyuga will be (2056 + 3042)  which support  above prophecies  

- From Bhahudhanya Naam Samvatsaras : next 14 years there will be many catastopies seviour drouth and floods., bload bath,and seviour wars will happen, and many destructions will  occure.
  - Bhahudhanya 1878, 1938, 1998, 2058
  - Estimate (2058-2072)  
  - Assume that 2072 is end of 5118 of kaliyuga and 1/7 population survived the start of kaliyuga will be 5118 (2072 + 3046BC) or
    - start of kaliyuga 5118-2072 = 3046BC
  - Assume that  kaliyuga start at 3042BC then 5118 kaliyuga (2076) then 
   - From Estimate 2058-2072 pralays and war can happen
   - by 2076 world population will be 1/7 which satisfies both 

- From Eashwara Naam Samvatsar to end of Vikrama Naam Samavatsaras  1 out of 7 villages and 1 out of 7 houses will survive  
  - Vikrama 	1880, 1940, 2000, 2060
- In  end of 5118 kaliyuga 1/7 world population will survive there is other prophecies
    - (start of kaliyuga) + 2060 <= 5118  = = > star of kaliyuga <= 3058 BC


From Bhahudhanya Naam Samvatsaras : next 14 years there will be many catastopies seviour drouth and floods., bload bath,and seviour wars will happen, and many destructions will  occure.
- Estimate (2058-2072)  as end of 5118 (2072 + 3046BC) there will be only 1/7 survive
Bhahudhanya 	1878, 1938, 1998, 2058
Dhatha 	1876, 1936, 1996, 2056

- Estimated time  aug 2056  to  feb 2057 
 
Dhatha 	1876, 1936, 1996, 2056
Eashwara 	1877, 1937, 1997, 2057

https://youtu.be/FD0VQ0Jo_NU?t=3541
Bhahudhanya Naam Samvatsaras  in banagaupally 5 years old nagaiya boy will read vedas without any one teaching him vedas then tiger will come to banagaupally and black face vanagrudu (half monkey and half man) will cicle around the village and leave 
Bhahudhanya 	1878, 1938, 1998, 2058 


https://youtu.be/FD0VQ0Jo_NU?t=3643
In plavanga naama samvatsaram there will be elicpes where sun will be visible is shape of a ring   
Plavanga 	1907, 1967, 2027, 2087

  

https://www.youtube.com/watch?v=FD0VQ0Jo_NU&t=2445s
From Eashwara Naam Samvatsar to end of Vikrama Naam Samavatsaras  1 out of 7 villages and 1 out of 7 houses will survive
- (Eashwara 2057 -  Vikrama 2060 )
- There is other estimate  end of 5118 kaliyuga 1/7 world population will survive 
- Vikrama 	1880, 1940, 2000, 2060
- Estimate start of kaliyuga :  (start of kaliyuga) + 2060 <= 5118  = = > star of kaliyuga <= 3058 BC


https://www.youtube.com/embed/G68ngdKd7gU?start=766
Oh Great people at the end of  5118 Kaliyuga year  in the entire world only 1/7 of population will be survied
- Estimate (5118 -3042 = 2076, 5118 -3102 = 2016, 5118- 3058 = 2060)
- Estimate time 2060, 2076 (1/7th population survive)

https://www.youtube.com/embed/G68ngdKd7gU?start=766
Oh Great people at the end of  5118 Kaliyuga year (2018 AC)  in the entire world only 1/7 of population will be survied 

https://www.youtube.com/embed/G68ngdKd7gU?start=810
In Vijaya Naam Samavatsara  Ashada Masa Śud'dha_Sapthami(17th Moon phase) i will give darshan to devotees and start dharma paripalana(Daramic Rule) before that 1/7 of sinfull people will be perished.
- Estimate it will happen after 5118  when 1/7 population survives 
- 2073 + start of kaliyuga <= 5118 => start of kaliyuga < 3045
- Vijaya 	1893, 1953, 2013, 2073
- Estimated time 2073 (start of kaliyuga at 3058)  

https://www.youtube.com/embed/VwGOH_c4OfQ?start=1664
After 5118 Kaliyuga year (2076)  before Aananda Naam Samvatsaras (2094): For 1 Pōka cekka (areca nut or beetel nut) you will get hand full of rice (పుట్టెడు బియ్యం).
Meaning
- In between  2076 and 2094 due to war, famine, dought, flood there will be a seviour shotage of food
  - due to war lot of people will die (only 1/7 of world population will be alive) less demand for rice so  price of rice can be fall down  
  - there will be huge agriculture developement 
  - and over-rice production will occure due (less demand and high supply) the cost of rice will be reduced very low  and they will sell one hand full of rice for 1 beetel-nut(Rs 1)
  - (5118 -30042 = 2076, 5118 -3102 = 2016)
  - Aananda 	1914, 1974, 2034, 2094
  - Estimated period 2016-2034 or  2076-2094


https://youtu.be/FD0VQ0Jo_NU?t=3075
From Bhahudhanya  to Nanadana  nama samvatsar :(2058-2072)
 In srisailam  malikarjura temple smoke file will start and temple shikaram will be on fire and and fall on ground 
- Inside temple deitys will come life and dance from village to village then sinfull people start to fear. 
- Lord Malikarjura will start to talk with people due to some people will die 
- Due to rain of weapons many will die

https://www.youtube.com/watch?v=FD0VQ0Jo_NU&t=4924s
In khara nama samvatsar the Glories (Mahimalu) of me(sriman naranaya) will be know and entire world village and cites blood rain will fall 
Khara 	1891, 1951, 2011, 2071

https://youtu.be/FD0VQ0Jo_NU?t=5171
From pashu nama samvatsar to  nandana nama samavatsara all water will dry
Khara 	1891, 1951, 2011, 2071
Nandana 	1892, 1952, 2012, 2072 

    
https://www.youtube.com/embed/VwGOH_c4OfQ?start=1752
Bezawada Indrakeela hill తొమ్మిది మూరల స్త్రీ (9 elite  స్త్రీ ) will be born and sinfull people shall be beheaded by holding there head.

https://www.youtube.com/embed/VwGOH_c4OfQ?start=1761
In Palnati seema Bhadra maha kaali shall be born and destroy all village and cites.

Part 2 Volume-II 
From village to village one shakti(energy) shall be born and it will cry like a goat(sheep) due to which some people will die.

In mangalagiri mayavadhi's vaishnavas divide into two groups due to conflicts and fight each other and dies.
Information about mangalagiri :https://www.mangalagiri.org/temple.html


 



Mandapaludu would talk with humans in Malayalam.

Mandapaludu = https://www.wisdomlib.org/definition/mandapala
https://www.timeforthought.net/2016/07/maha-bharata-some-hidden-gems-7.html
https://www.vyasaonline.com/2017/01/17/sarangopakhyana-the-story-of-saranga-birds/mahabharata/


https://youtu.be/FD0VQ0Jo_NU?t=1699
In Malayalam there will be no more men  



https://hindupad.com/macherla-chennakesava-swamy-temple-lakshmi-chennakeshava-swamy-temple/

From Gandikota Muṇḍamōpulu(Muṇḍamōpulu Forearms ) persons will come to kurnool with madness 


https://www.youtube.com/embed/G68ngdKd7gU?start=654
In nandana Naam Samavatsaras lot of stars(commets) will fall due to which earth will shake
Nandana 	1892, 1952, 2012, 2072
Estimate : 2072


https://www.youtube.com/embed/G68ngdKd7gU?star=666
In Pingala Naam Samavatsaras Ghōramaina(Horrible, dreadful, terrible) will start and it will continous till Kalayukthi Naam Samavatsaras in (uttara desham )[approximate: north india or  uttar pradesh or  nothen country] 

Pingala 	1917, 1977, 2037, 2097
Kalayukthi 	1918,1978, 2038, 2098

https://youtu.be/FD0VQ0Jo_NU?t=5888
Aananda Naam Samvatsaras mārgaśira  bhalual asthami  guruvāraṁ srisailam Lord  malikarjura with goddess bramarammbha will vindya mountain
  
mārgaśir: (November/December 9th month in hindu)
aṣṭami  : eighth day after the new or full moon
guruvāraṁ : Thursday
 
Aananda 	1914, 1974, 2034, 2094 

https://www.youtube.com/watch?v=FD0VQ0Jo_NU&t=5900s

From Durmukhi Naama Samvatsara  Kaarthika sudha chaturthi  start with  suppressing sinful person  and goes to maha pralays
This pralays will start at Roudri Naama Samvatsara Kaarthika masa 
- Kaarthika masa : October/November
- is the fourth day (Tithi) of both waxing and waning phase 
- Durmukhi 	1896, 1956, 2016, 2076
- Roudri 	1920, 1980, 2040, 2100
- Estimate : 2076-2100  because supressing sinful person can't happen after 2016 (present timeline : because in future  adharma should increase war should happen  so it will happen after after 2076(5118 AK ) )
 

108 years , 1000 years
https://youtu.be/FD0VQ0Jo_NU?t=5926
vijaya naama samvatsara kaliki will marriage matru-vamsham vijayawada-girl and will come with rishi, yogi, sidhis, avadhuda, paramahamsa's and rule 108 years after my descandace will rule  1000 year
- Vijaya 	1893, 1953, 2013, 2073

(2016) āṣāḍhama sudha sampthami  give darsham to devotees and to darma-paripalana before that from 7 houses 6 house sinful persons will be destroyed
24th year old rule 108 years and his descandes will rule 1000 years(2076 + 108 + 1000 = 3184 AC , 6226 kaliyuga) 



2021-2060 https://www.youtube.com/watch?v=wfSaig_cg1g

* https://laxmimadhav.wordpress.com/2016/10/01/kalagnanam/
23. India will participate in a war and the Indian Capital New Delhi will be bombed, in the year Krodhi (2024-25) the capital will be shifted from New Delhi to Anegondi (Near Hampi, Karnataka State). And in the same year i.e. Krodhi (2024-25), the Nellore region will be submerged.

51. Hampi(Karnataka) may probably be destroyed by Nuclear Attack.

79. A direct Disciple of Lord Parasurama and Acharya Nagarjuna, Sri Sanaari Visweswara and other Sidhdha Purushas (probably Aghori sect), with his Alchemy will clear the debts of the Country and save from financial difficulties, and later link all the rivers and save from severe drought.

80. Only 1/7th of the World population will survive by the end of Third World War.
* kalagnanam : temple to visit
Kalagananam will contain prediction about 5000(1958) year after kaliyugan to duration of 108(2066) years


* Nostradamus
https://holybooks.com/wp-content/uploads/The-Complete-works-of-Nostradamus.pdf

I have composed books of prophecies, each containing one hundred astronomical quatrains, which I want to condense somewhat obscurely. The work comprises prophecies from today to the year 3767


L. De l'aquatique triplicité naistra, D'vn qui fera le Ieudy pour sa feste: Son bruit, loz, regne, sa puissance croistra, Par terre & mer aux Oriens tempeste.
=From the three water signs will be born a man who will celbrate Thursday as his holiday. His renown, praise, rule and power will grow on land and sea, bringing trouble to the East.=

LI. Vn Duc cupide son ennemy ensuyure, Dans entrera empeschant la phalange, Hastez à pied si pres viendront poursuyure, Que la iournee conflite pres de Gange.
=A Duke eager to follow his enemy Will enter within impeding the phalanx: Hurried on foot they will come to pursue so closely That the day will see a conflict near Ganges.=

LXXV. Tant attendu ne reuiendra iamais, Dedans l'Europe en Asie apparoistra: Vn de la ligue yssu du grand Hermes, Et sur tous Roys des Orients croistra.
=Long awaited he will never return In Europe, he will appear in Asia: One of the league issued from the great Hermes, And he will grow over all the Kings of the East.=

LXXVI. Le grand Senat discernera la pompe, A l'vn qu'apres sera vaincu chassé: Ses adherans seront à son de trompe Biens publiez, ennemis dechassez. The great Senate will ordain the triumph For one who afterwards will be vanquished, driven out: At the sound of the trumpet of his adherents there will be Put up for sale their possessions, enemies expelled. LXXVII. Trente adherans de l'ordre des quirettes Bannis, leurs biens donnez ses aduersaires: Tous leurs bienfaits seront pour demerites, Classe espargie deliurez aux Corsaires. Thirty adherents of the order of "Quirites" Banished, their possessions given their adversaries: All their benefits will be taken as misdeeds, Fleet dispersed, delivered to the Corsairs. Downloaded from https://www.holybooks.com https://www.holybooks.com/the-complete-works-of-nostradamus-pdf/

